-- TABLE PPSNEPL.HAZARD_DISPOSE_INPUT

CREATE  TABLE "PPSNEPL"."HAZARD_DISPOSE_INPUT"(
  "NDC_NUMBER" VARCHAR2(50 ) NOT NULL,
  "PRODUCT_NAME" VARCHAR2(50 ),
  "PRIMARY_EPA_CODE" VARCHAR2(50 ),
  "WASTE_SORT_CODE" VARCHAR2(50 ),
  "DOT_SHIPPING_NAME" VARCHAR2(150 ),
  "LOAD_STATUS" VARCHAR2(150),
  "LOAD_DTM" TIMESTAMP(6)
)
)

/

-- ADD KEYS FOR TABLE PPSNEPL.HAZARD_DISPOSE_INPUT

ALTER TABLE "PPSNEPL"."HAZARD_DISPOSE_INPUT" ADD CONSTRAINT "PK_HAZARDDISPOSEINPUT" PRIMARY KEY ("NDC_NUMBER")
/
