-- TABLE PPSNEPL.HAZARD_HANDLE_INPUT

CREATE TABLE "PPSNEPL"."HAZARD_HANDLE_INPUT"(
  "PRODUCT_NAME" VARCHAR2(50 ) NOT NULL,
  "SOURCE_NAME" VARCHAR2(50 ),
  "AHFS_PHARM_CLASS" VARCHAR2(150 ),
  "LOAD_STATUS" VARCHAR2(150),
  "LOAD_DTM" TIMESTAMP(6)
)
/

-- ADD KEYS FOR TABLE PPSNEPL.HAZARD_HANDLE_INPUT

ALTER TABLE "PPSNEPL"."HAZARD_HANDLE_INPUT" ADD CONSTRAINT "PK_HAZARDHANDLEINPUT" PRIMARY KEY ("PRODUCT_NAME")
/
