SET DEFINE OFF;
Insert into PPSNEPL.EPL_VA_DFS
   (ID, VADF_NAME, VADF_TYPE, MULTI_SELECT_YN, VADF_USAGES, 
    CREATED_BY, CREATED_DTM)
 Values
   (149, 'primary.epa.code', 'STRING', 'N', 'P', 
    'DEVELOPER', TO_TIMESTAMP('5/6/2013 12:00:00.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into PPSNEPL.EPL_VA_DFS
   (ID, VADF_NAME, VADF_TYPE, MULTI_SELECT_YN, VADF_USAGES, 
    CREATED_BY, CREATED_DTM)
 Values
   (150, 'waste.sort.code', 'STRING', 'N', 'P', 
    'DEVELOPER', TO_TIMESTAMP('5/6/2013 12:00:00.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
Insert into PPSNEPL.EPL_VA_DFS
   (ID, VADF_NAME, VADF_TYPE, MULTI_SELECT_YN, VADF_USAGES, 
    CREATED_BY, CREATED_DTM)
 Values
   (151, 'dot.shipping.name', 'STRING', 'N', 'P', 
    'DEVELOPER', TO_TIMESTAMP('5/6/2013 12:00:00.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
COMMIT;
