/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.common.vo;


/**
 * This enum is used to specify different types of session preferences.
 */
public enum SessionPreferenceType {

    /** DEFAULT_SEARCH_TEMPLATE_ID */
    DEFAULT_SEARCH_TEMPLATE_ID,

    /** DEFAULT_PROD_PRINT_TEMPLATE_ID */
    DEFAULT_PROD_PRINT_TEMPLATE_ID,

    /** DEFAULT_OI_PRINT_TEMPLATE_ID */
    DEFAULT_OI_PRINT_TEMPLATE_ID,

    /** DEFAULT_NDC_PRINT_TEMPLATE_ID */
    DEFAULT_NDC_PRINT_TEMPLATE_ID,

    /** LAST_SEARCH_DOMAIN */
    LAST_SEARCH_DOMAIN,

    /** LAST_REQUEST_SEARCH_DOMAIN */
    LAST_REQUEST_SEARCH_DOMAIN,

    /** LAST_REQUEST_PEND_ADD */
    LAST_REQUEST_PEND_ADD,

    /** LAST_REQUEST_PEND_2ND */
    LAST_REQUEST_PEND_2ND,

    /** LAST_REQUEST_PEND_MOD */
    LAST_REQUEST_PEND_MOD,

    /** LAST_REQUEST_PEND_2ND_MOD */
    LAST_REQUEST_PEND_2ND_MOD,

    /** LAST_REQUEST_ALL_REQ */
    LAST_REQUEST_ALL_REQ,

    /** LAST_REQUEST_UNDER_REVIEW */
    LAST_REQUEST_UNDER_REVIEW,

    /** LAST_REQUEST_MARK_PSR */
    LAST_REQUEST_MARK_PSR,

    /** LAST_REQUEST_CHANGE_REQ */
    LAST_REQUEST_CHANGE_REQ,

    /** LAST_REQUEST_NOT_LAST_REV */
    LAST_REQUEST_NOT_LAST_REV,

    /** LAST_DOMAIN_REQUEST_PEND_ADD */
    LAST_DOMAIN_REQUEST_PEND_ADD,

    /** LAST_DOMAIN_REQUEST_PEND_2ND */
    LAST_DOMAIN_REQUEST_PEND_2ND,

    /** LAST_DOMAIN_REQUEST_PEND_2ND_MOD */
    LAST_DOMAIN_REQUEST_PEND_2ND_MOD,

    /** LAST_DOMAIN_REQUEST_ALL_REQ */
    LAST_DOMAIN_REQUEST_ALL_REQ,

    /** LAST_DOMAIN_REQUEST_UNDER_REVIEW */
    LAST_DOMAIN_REQUEST_UNDER_REVIEW,

    /** LAST_DOMAIN_REQUEST_MARK_PSR */
    LAST_DOMAIN_REQUEST_MARK_PSR,

    /** LAST_DOMAIN_REQUEST_CHANGE_REQ */
    LAST_DOMAIN_REQUEST_CHANGE_REQ,

    /** LAST_DOMAIN_REQUEST_NOT_LAST_REV */
    LAST_DOMAIN_REQUEST_NOT_LAST_REV,


    /** BEGIN: last simple search search values */

    /** LAST_SIMPLE_ENTITY_TYPE */
    LAST_SIMPLE_ENTITY_TYPE,

    /** LAST_SIMPLE_STRENGTH */
    LAST_SIMPLE_STRENGTH,

    /** LAST_SIMPLE_SEARCH_FIELD */
    LAST_SIMPLE_SEARCH_FIELD,

    /** LAST_SIMPLE_CATS */
    LAST_SIMPLE_CATS,

    /** LAST_SIMPLE_SUBCATS */
    LAST_SIMPLE_SUBCATS,

    /** LAST_SIMPLE_DOSAGE_FORM */
    LAST_SIMPLE_DOSAGE_FORM,

    /** LAST_SIMPLE_SEARCH_TYPE */
    LAST_SIMPLE_SEARCH_TYPE,

    /** LAST_SIMPLE_ITEM_STATUS */
    LAST_SIMPLE_ITEM_STATUS,

    /** LAST_SIMPLE_ITEM_REQUEST */
    LAST_SIMPLE_ITEM_REQUEST,

    /** END: last simple search search values */

    /** BEGIN: last domain search values */

    /** LAST_DOMAIN_ITEM_STATUS */
    LAST_DOMAIN_ITEM_STATUS,

    /** LAST_DOMAIN_ITEM_REQUEST */
    LAST_DOMAIN_ITEM_REQUEST,

    /** LAST_DOMAIN_SEARCH_FIELD */
    LAST_DOMAIN_SEARCH_FIELD,

    /** END: last domain search search values */

    /** SHORT_DATE_FORMAT */
    SHORT_DATE_FORMAT,

    /** LONG_DATE_FORMAT */
    LONG_DATE_FORMAT,

    /** TIME_FORMAT */
    TIME_FORMAT,

    /** TABLE_ROW_COUNT */
    TABLE_ROW_COUNT,

    /** DRUG_CLASS_SORT */
    DRUG_CLASS_SORT,

    /** HOME_PAGE_DEFAULT */
    HOME_PAGE_DEFAULT,
    
    /** FDB_DEVICES */
    FDB_DEVICES,
    
    /** FDB_RX_OTC */
    FDB_RX_OTC,
    
    /** FDB_SINGLE_INGREDIENT */
    FDB_SINGLE_INGREDIENT,
    
    /** FDB_OBSOLETE_DRUGS */
    FDB_OBSOLETE_DRUGS,
    
    /** FDB_PRIVATE_LABELERS */
    FDB_PRIVATE_LABELERS,
    
    /** FDB_REPACKAGERS */
    FDB_REPACKAGERS,
    
    /** FDB_STATUS_CODE */
    FDB_STATUS_CODE,
    
    /** FDB_STATUS_CODE_ACTIVE */
    FDB_STATUS_CODE_ACTIVE,
    
    /** FDB_STATUS_CODE_REPLACED */
    FDB_STATUS_CODE_REPLACED,
    
    /** FDB_STATUS_CODE_RETIRED */
    FDB_STATUS_CODE_RETIRED,
    
    /** FDB_STATUS_CODE_INACTIVE */
    FDB_STATUS_CODE_INACTIVE,
    
    /** FDB_STATUS_CODE_UNASSOCIATED */
    FDB_STATUS_CODE_UNASSOCIATED,
    
    /** FDB_NAME_TYPE */
    FDB_NAME_TYPE,
    
    /** FDB_NAME_TYPE */
    FDB_PHONETIC_SEARCH,
    
    /** FDB_NAME_TYPE */
    FDB_SEARCH_METHODS,
    
    /** FDB_PACKAGED_DRUG */
    FDB_PACKAGED_DRUG;
    
}
