/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Aug 16, 2008 12:46:31 PM by Hibernate Tools 3.2.0.beta8



/**
 * EplDfMedRtDfAssocDoKey generated by hbm2java
 * @hibernate.class
 */
public class EplDfMedRtDfAssocDoKey implements java.io.Serializable {

    // Fields
    
    private static final long serialVersionUID = 1L;

    private Long dosageFormIdFk;
    private Long medRouteIdFk;

    // Constructors

    /** default constructor */
    
    public EplDfMedRtDfAssocDoKey() {
    }

    /** full constructor */
    
    public EplDfMedRtDfAssocDoKey(Long dosageFormIdFk, Long medRouteIdFk) {
        this.dosageFormIdFk = dosageFormIdFk;
        this.medRouteIdFk = medRouteIdFk;
    }

    // Property accessors
    public Long getDosageFormIdFk() {
        return this.dosageFormIdFk;
    }

    public void setDosageFormIdFk(Long dosageFormIdFk) {
        this.dosageFormIdFk = dosageFormIdFk;
    }

    public Long getMedRouteIdFk() {
        return this.medRouteIdFk;
    }

    public void setMedRouteIdFk(Long medRouteIdFk) {
        this.medRouteIdFk = medRouteIdFk;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplDfMedRtDfAssocDoKey)) {
            return false;
        }
        
        EplDfMedRtDfAssocDoKey castOther = (EplDfMedRtDfAssocDoKey) other;

        return ((this.getDosageFormIdFk() == castOther.getDosageFormIdFk()) || (this.getDosageFormIdFk() != null
            && castOther.getDosageFormIdFk() != null && this.getDosageFormIdFk().equals(castOther.getDosageFormIdFk())))
            && ((this.getMedRouteIdFk() == castOther.getMedRouteIdFk()) || (this.getMedRouteIdFk() != null
                && castOther.getMedRouteIdFk() != null && this.getMedRouteIdFk().equals(castOther.getMedRouteIdFk())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getDosageFormIdFk() == null ? 0 : this.getDosageFormIdFk().hashCode());
        result = 37 * result + (getMedRouteIdFk() == null ? 0 : this.getMedRouteIdFk().hashCode());
        
        return result;
    }

}
