/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


/**
 * EplDfNounDoKey generated by hbm2java
 * @hibernate.class
 */
public class EplDfNounDoKey implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    // Fields

    private Long dosageFormEplIdFk;
    private String noun;

    // Constructors

    /** default constructor */

    public EplDfNounDoKey() {
    }

    /** full constructor */

    public EplDfNounDoKey(Long dosageFormEplIdFk, String noun) {
        this.dosageFormEplIdFk = dosageFormEplIdFk;
        this.noun = noun;
    }

    // Property accessors

    public Long getDosageFormEplIdFk() {
        return this.dosageFormEplIdFk;
    }

    public void setDosageFormEplIdFk(Long dosageFormEplIdFk) {
        this.dosageFormEplIdFk = dosageFormEplIdFk;
    }

    public String getNoun() {
        return this.noun;
    }

    public void setNoun(String noun) {
        this.noun = noun;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplDfNounDoKey)) {
            return false;
        }
        
        EplDfNounDoKey castOther = (EplDfNounDoKey) other;

        return ((this.getDosageFormEplIdFk() == castOther.getDosageFormEplIdFk()) || (this.getDosageFormEplIdFk() != null
            && castOther.getDosageFormEplIdFk() != null && this.getDosageFormEplIdFk().equals(
                castOther.getDosageFormEplIdFk())))
            && ((this.getNoun() == castOther.getNoun()) || (this.getNoun() != null && castOther.getNoun() != null && this
                .getNoun().equals(castOther.getNoun())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getDosageFormEplIdFk() == null ? 0 : this.getDosageFormEplIdFk().hashCode());
        result = 37 * result + (getNoun() == null ? 0 : this.getNoun().hashCode());
        
        return result;
    }

}
