/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


import java.util.Date;


/**
 * EplDoseUnitSynonymDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplDoseUnitSynonymDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String SYNONYM = "doseUnitSynonym";
    public static final String ITEM_STATUS = "itemStatus";
    public static final String REQUEST_STATUS = "requestStatus";
    private static final long serialVersionUID = 1L;

    private EplDoseUnitSynonymDoKey key;
    private EplDoseUnitDo eplDoseUnit;

    // Constructors

    /**
     * default constructor
     */
    public EplDoseUnitSynonymDo() {
    }

    /**
     * minimal constructor
     * 
     * @param key EplDoseUnitSynonymDoKey
     * @param requestStatus String
     * @param itemStatus String
     * @param revisionNumber Long
     * @param createdBy String
     * @param createdDtm Date
     */
    public EplDoseUnitSynonymDo(EplDoseUnitSynonymDoKey key, String requestStatus, String itemStatus, Long revisionNumber,
                                String createdBy, Date createdDtm) {
        this.key = key;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /**
     * full constructor
     * 
     * @param key EplDoseUnitSynonymDoKey
     * @param doseUnitSynonym String
     * @param requestStatus String
     * @param itemStatus String
     * @param rejectReasonText String
     * @param inactivationDate Date
     * @param revisionNumber Long
     * @param createdBy String
     * @param createdDtm Date
     * @param lastModifiedBy String
     * @param lastModifiedDtm Date
     * @param eplDoseUnit EplDoseUnitDo
     */
    public EplDoseUnitSynonymDo(EplDoseUnitSynonymDoKey key, String doseUnitSynonym, String requestStatus,
                                String itemStatus, String rejectReasonText, Date inactivationDate, Long revisionNumber,
                                String createdBy, Date createdDtm, String lastModifiedBy, Date lastModifiedDtm,
                                EplDoseUnitDo eplDoseUnit) {
        this.key = key;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplDoseUnit = eplDoseUnit;
    }

    // Property accessors

    /**
     * 
     * @return EplDoseUnitSynonymDoKey
     */
    public EplDoseUnitSynonymDoKey getKey() {
        return this.key;
    }

    /**
     * 
     * @param key EplDoseUnitSynonymDoKey
     */
    public void setKey(EplDoseUnitSynonymDoKey key) {
        this.key = key;
    }

    /**
     * 
     * @return EplDoseUnitDo
     */
    public EplDoseUnitDo getEplDoseUnit() {
        return this.eplDoseUnit;
    }

    /**
     * 
     * @param eplDoseUnit EplDoseUnitDo
     */
    public void setEplDoseUnit(EplDoseUnitDo eplDoseUnit) {
        this.eplDoseUnit = eplDoseUnit;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * 
     * @param other Object
     * @return boolean
     * 
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#equals(java.lang.Object)
     */
    public boolean equals(Object other) {

        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplDoseUnitSynonymDo)) {
            return false;
        }

        EplDoseUnitSynonymDo castOther = (EplDoseUnitSynonymDo) other;

        return ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this
            .getKey().equals(castOther.getKey())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())));
    }

    /**
     * 
     * @return int
     * 
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#hashCode()
     */
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());

        return result;
    }
}
