

package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Nov 18, 2011 1:24:26 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;


/**
 * EplFdbGenericNameDo generated by hbm2java
 * 
 * @hibernate.class
 * 
 */
public class EplFdbGenericNameDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
        java.io.Serializable {

    // Fields
    public static final String FDB_GENERIC_DRUG_NAME = "fdbGenericDrugname";
    public static final String EPL_GENERIC_NAME_FK = "eplGenericNameFk";

    private String fdbGenericDrugname;
    private Long eplGenericNameFk;
    private String createdBy;
    private Date createdDtm;
    private String lastModifiedBy;
    private Date lastModifiedDtm;

    private static final long serialVersionUID = 1L;

    /**
     * Default Constructor
     */
    public EplFdbGenericNameDo() {
    }

    /**
     * Minimal Constructor
     * 
     * @param fdbGenericDrugname
     * @param createdBy
     * @param createdDtm
     */
    public EplFdbGenericNameDo(String fdbGenericDrugname, String createdBy, Date createdDtm) {
        this.fdbGenericDrugname = fdbGenericDrugname;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /**
     * Full Constructor
     * 
     * @param id
     * @param fdbGenericDrugname
     * @param eplGenericNameFk
     * @param createdBy
     * @param createdDtm
     * @param lastModifiedBy
     * @param lastModifiedDtm
     * @param eplFdbGenericNameAssocs
     */
    public EplFdbGenericNameDo(String fdbGenericDrugname, Long eplGenericNameFk,
                               String createdBy, Date createdDtm, String lastModifiedBy, Date lastModifiedDtm) {
        this.fdbGenericDrugname = fdbGenericDrugname;
        this.eplGenericNameFk = eplGenericNameFk;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
    }

    /**
     * 
     * @return fdbGenericDrugname
     */
    public String getFdbGenericDrugname() {
        return this.fdbGenericDrugname;
    }

    /**
     * 
     * @param fdbGenericDrugname
     */
    public void setFdbGenericDrugname(String fdbGenericDrugname) {
        this.fdbGenericDrugname = fdbGenericDrugname;
    }

    /**
     * 
     * @return eplGenericNameFk
     */
    public Long getEplGenericNameFk() {
        return eplGenericNameFk;
    }

    /**
     * 
     * @param eplGenericNameFk
     */
    public void setEplGenericNameFk(Long eplGenericNameFk) {
        this.eplGenericNameFk = eplGenericNameFk;
    }

    /**
     * 
     */
    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * 
     */
    @Override
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public Date getCreatedDtm() {
        return this.createdDtm;
    }

    @Override
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    @Override
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    @Override
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @Override
    public Date getLastModifiedDtm() {
        return this.lastModifiedDtm;
    }

    @Override
    public void setLastModifiedDtm(Date lastModifiedDtm) {
        this.lastModifiedDtm = lastModifiedDtm;
    }

    /* (non-Javadoc)
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#toString()
     */
    @Override
    public String toString() {
        return "EplFdbGenericNameDo [fdbGenericDrugname="
               + fdbGenericDrugname + ", eplGenericNameFk=" + eplGenericNameFk + ", createdBy=" + createdBy + ", createdDtm="
               + createdDtm + ", lastModifiedBy=" + lastModifiedBy + ", lastModifiedDtm=" + lastModifiedDtm + "]";
    }

    /* (non-Javadoc)
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((createdBy == null) ? 0 : createdBy.hashCode());
        result = prime * result + ((createdDtm == null) ? 0 : createdDtm.hashCode());
        result = prime * result + ((eplGenericNameFk == null) ? 0 : eplGenericNameFk.hashCode());
        result = prime * result + ((fdbGenericDrugname == null) ? 0 : fdbGenericDrugname.hashCode());
        result = prime * result + ((lastModifiedBy == null) ? 0 : lastModifiedBy.hashCode());
        result = prime * result + ((lastModifiedDtm == null) ? 0 : lastModifiedDtm.hashCode());
        return result;
    }

    /* (non-Javadoc)
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!super.equals(obj))
            return false;
        if (getClass() != obj.getClass())
            return false;
        EplFdbGenericNameDo other = (EplFdbGenericNameDo) obj;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        } else if (!createdBy.equals(other.createdBy))
            return false;
        if (createdDtm == null) {
            if (other.createdDtm != null)
                return false;
        } else if (!createdDtm.equals(other.createdDtm))
            return false;
        if (eplGenericNameFk == null) {
            if (other.eplGenericNameFk != null)
                return false;
        } else if (!eplGenericNameFk.equals(other.eplGenericNameFk))
            return false;
        if (fdbGenericDrugname == null) {
            if (other.fdbGenericDrugname != null)
                return false;
        } else if (!fdbGenericDrugname.equals(other.fdbGenericDrugname))
            return false;
        if (lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        } else if (!lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (lastModifiedDtm == null) {
            if (other.lastModifiedDtm != null)
                return false;
        } else if (!lastModifiedDtm.equals(other.lastModifiedDtm))
            return false;
        return true;
    }
}
