/**
 * Source file created in 2011 by Southwest Research Institute
 * 
 * Generated Oct 25, 2011 3:04:47 PM by Hibernate Tools 3.2.4.GA
 */


package gov.va.med.pharmacy.peps.domain.common.model;


import java.util.Date;


/**
 * EplFdbUpdateDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplFdbUpdateDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
        java.io.Serializable {

    // Fields
    public static final String GCNSEQNO = "gcnSeqno";
    public static final String EPL_ID = "eplId";
    public static final String MESSAGE = "message";
    public static final String VA_PRODUCT_NAME = "vaProductName";
    public static final String NDC = "ndc";
    public static final String FDB_PRODUCT_NAME = "fdbProductName";
    public static final String NDC_ID_FK = "ndcIdFk";
    public static final String PRODUCT_ID_FK = "productIdFk";

    private static final long serialVersionUID = 1L;

    private Long eplId;
    private Long gcnSeqno;
    private String message;
    private String vaProductName;
    private String ndc;
    private String fdbProductName;
    private Long ndcIdFk;
    private Long productIdFk;
    private String createdBy;
    private Date createdDtm;
    private String lastModifiedBy;
    private Date lastModifiedDtm;

    /**
     * Default Constructor
     */
    public EplFdbUpdateDo() {
    }

    /**
     * @param eplId eplId
     * @param name name
     * @param gcnSeqNo gcnSeqNo
     * @param productYn productYn
     * @param message message
     * @param createdBy createdBy
     * @param createdDtm createdDtm
     * @param lastModifiedBy lastModifiedBy
     * @param lastModifiedDtm lastModifiedDtm
     */
    public EplFdbUpdateDo(Long eplId, String ndc, String itemType, Long gcnSeqno, String message, 
                          String vaProductName, String fdbProductName,  
                          Long ndcIdFk, Long productIdFk, String createdBy, 
                          Date createdDtm, String lastModifiedBy,Date lastModifiedDtm) {

        this.eplId = eplId;
        this.gcnSeqno = gcnSeqno;
        this.ndc = ndc;
        this.message = message;
        this.vaProductName = vaProductName;
        this.fdbProductName = fdbProductName;
        this.ndcIdFk = ndcIdFk;
        this.productIdFk = productIdFk;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
    }
    
    
    /**
     * 
     * @return eplId
     */
    public Long getEplId() {
        return eplId;
    }

    /**
     * 
     * @param eplId
     */
    public void setEplId(Long eplId) {
        this.eplId = eplId;
    }
    
    /**
     * 
     * @return gcnSeqno
     */
    public Long getGcnSeqno() {
        return gcnSeqno;
    }

    /**
     * 
     * @param gcnSeqno
     */
    public void setGcnSeqno(Long gcnSeqno) {
        this.gcnSeqno = gcnSeqno;
    }

    /**
     * 
     * @return message
     */
    public String getMessage() {
        return message;
    }

    /**
     * 
     * @param message
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * 
     * @return vaProductName
     */
    public String getVaProductName() {
        return vaProductName;
    }

    /**
     * 
     * @param vaProductName
     */
    public void setVaProductName(String vaProductName) {
        this.vaProductName = vaProductName;
    }

    /**
     * 
     * @return fdbProductName
     */
    public String getFdbProductName() {
        return fdbProductName;
    }

    /**
     * 
     * @param fdbProductName
     */
    public void setFdbProductName(String fdbProductName) {
        this.fdbProductName = fdbProductName;
    }

    /**
     * getNdc.
     * @return ndc
     */
    public String getNdc() {
        return ndc;
    }

    /**
     * setNdc.
     * @param ndc
     */
    public void setNdc(String ndc) {
        this.ndc = ndc;
    }
    
    
    /**
     * 
     * @return ndcIdFk
     */
    public Long getNdcIdFk() {
        return ndcIdFk;
    }

    /**
     * 
     * @param ndcIdFk
     */
    public void setNdcIdFk(Long ndcIdFk) {
        this.ndcIdFk = ndcIdFk;
    }

    /**
     * 
     * @return productIdFk
     */
    public Long getProductIdFk() {
        return productIdFk;
    }

    /**
     * 
     * @param productIdFk
     */
    public void setProductIdFk(Long productIdFk) {
        this.productIdFk = productIdFk;
    }

    /* (non-Javadoc)
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#toString()
     */
    @Override
    public String toString() {
        return "EplFdbUpdateDo [gcnSeqno=" + gcnSeqno + ", eplId=" + eplId +
        		"message=" + message + ", vaProductName=" + vaProductName + 
        		", ndc=" + ndc + 
        		", fdbProductName=" + fdbProductName +  ", ndcIdFk=" + ndcIdFk + ", productIdFk=" + 
        		productIdFk + ", createdBy=" + createdBy + ", createdDtm=" + createdDtm + 
        		", lastModifiedBy=" + lastModifiedBy + ", lastModifiedDtm=" + lastModifiedDtm + "]";
    }

    /* (non-Javadoc)
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((createdBy == null) ? 0 : createdBy.hashCode());
        result = prime * result + ((createdDtm == null) ? 0 : createdDtm.hashCode());
        result = prime * result + ((fdbProductName == null) ? 0 : fdbProductName.hashCode());
        result = prime * result + ((ndc == null) ? 0 : ndc.hashCode());
        result = prime * result + ((gcnSeqno == null) ? 0 : gcnSeqno.hashCode());
        result = prime * result + ((eplId == null) ? 0 : eplId.hashCode());
        result = prime * result + ((lastModifiedBy == null) ? 0 : lastModifiedBy.hashCode());
        result = prime * result + ((lastModifiedDtm == null) ? 0 : lastModifiedDtm.hashCode());
        result = prime * result + ((message == null) ? 0 : message.hashCode());
        result = prime * result + ((ndcIdFk == null) ? 0 : ndcIdFk.hashCode());
        result = prime * result + ((productIdFk == null) ? 0 : productIdFk.hashCode());
        result = prime * result + ((vaProductName == null) ? 0 : vaProductName.hashCode());
        return result;
    }

    /* (non-Javadoc)
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!super.equals(obj))
            return false;
        if (getClass() != obj.getClass())
            return false;
        EplFdbUpdateDo other = (EplFdbUpdateDo) obj;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        } else if (!createdBy.equals(other.createdBy))
            return false;
        if (createdDtm == null) {
            if (other.createdDtm != null)
                return false;
        } else if (!createdDtm.equals(other.createdDtm))
            return false;
        if (fdbProductName == null) {
            if (other.fdbProductName != null)
                return false;
        } else if (!fdbProductName.equals(other.fdbProductName))
            return false;
        if (eplId == null) {
            if (other.eplId != null)
                return false;
        } else if (!eplId.equals(other.eplId))
            return false;
        if (lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        } else if (!lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (lastModifiedDtm == null) {
            if (other.lastModifiedDtm != null)
                return false;
        } else if (!lastModifiedDtm.equals(other.lastModifiedDtm))
            return false;
        if (message == null) {
            if (other.message != null)
                return false;
        } else if (!message.equals(other.message))
            return false;
        if (ndcIdFk == null) {
            if (other.ndcIdFk != null)
                return false;
        } else if (!ndcIdFk.equals(other.ndcIdFk))
            return false;
        if (ndc == null) {
            if (other.ndc != null)
                return false;
        } else if (!ndc.equals(other.ndc))
            return false;
        if (productIdFk == null) {
            if (other.productIdFk != null)
                return false;
        } else if (!productIdFk.equals(other.productIdFk))
            return false;
        if (vaProductName == null) {
            if (other.vaProductName != null)
                return false;
        } else if (!vaProductName.equals(other.vaProductName))
            return false;
        return true;
    }
}
