/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


import java.util.Date;


/**
 * EplHospitalLocationDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplHospitalLocationDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {
    private static final long serialVersionUID = 1L;

    // Fields

    private Long id;
    private String administrationTimes;
    private String hospitalLocation;
    private String shifts;
    private EplAdminScheduleDo eplAdminSchedule;

    // Constructors

    /** default constructor */

    public EplHospitalLocationDo() {
    }

    /** minimal constructor */

    public EplHospitalLocationDo(Long id, String hospitalLocation, String createdBy, Date createdDtm) {
        this.id = id;
        this.hospitalLocation = hospitalLocation;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */

    public EplHospitalLocationDo(Long id, String administrationTimes, String hospitalLocation, String shifts,
                                 String createdBy, Date createdDtm, String lastModifiedBy, Date lastModifiedDtm,
                                 EplAdminScheduleDo eplAdminSchedule) {
        this.id = id;
        this.administrationTimes = administrationTimes;
        this.hospitalLocation = hospitalLocation;
        this.shifts = shifts;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplAdminSchedule = eplAdminSchedule;
    }

    // Property accessors
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAdministrationTimes() {
        return this.administrationTimes;
    }

    public void setAdministrationTimes(String administrationTimes) {
        this.administrationTimes = administrationTimes;
    }

    public String getHospitalLocation() {
        return this.hospitalLocation;
    }

    public void setHospitalLocation(String hospitalLocation) {
        this.hospitalLocation = hospitalLocation;
    }

    public String getShifts() {
        return this.shifts;
    }

    public void setShifts(String shifts) {
        this.shifts = shifts;
    }

    public EplAdminScheduleDo getEplAdminSchedule() {
        return this.eplAdminSchedule;
    }

    public void setEplAdminSchedule(EplAdminScheduleDo eplAdminSchedule) {
        this.eplAdminSchedule = eplAdminSchedule;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("administrationTimes").append("='").append(getAdministrationTimes()).append("' ");
        buffer.append("hospitalLocation").append("='").append(getHospitalLocation()).append("' ");
        buffer.append("shifts").append("='").append(getShifts()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplHospitalLocationDo)) {
            return false;
        }
        
        EplHospitalLocationDo castOther = (EplHospitalLocationDo) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId()
            .equals(castOther.getId())))
            && ((this.getAdministrationTimes() == castOther.getAdministrationTimes()) || (this.getAdministrationTimes() != null
                && castOther.getAdministrationTimes() != null && this.getAdministrationTimes().equals(
                    castOther.getAdministrationTimes())))
            && ((this.getHospitalLocation() == castOther.getHospitalLocation()) || (this.getHospitalLocation() != null
                && castOther.getHospitalLocation() != null && this.getHospitalLocation().equals(
                    castOther.getHospitalLocation())))
            && ((this.getShifts() == castOther.getShifts()) || (this.getShifts() != null && castOther.getShifts() != null && this
                .getShifts().equals(castOther.getShifts())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())))
            && ((this.getEplAdminSchedule() == castOther.getEplAdminSchedule()) || (this.getEplAdminSchedule() != null
                && castOther.getEplAdminSchedule() != null && this.getEplAdminSchedule().equals(
                    castOther.getEplAdminSchedule())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getAdministrationTimes() == null ? 0 : this.getAdministrationTimes().hashCode());
        result = 37 * result + (getHospitalLocation() == null ? 0 : this.getHospitalLocation().hashCode());
        result = 37 * result + (getShifts() == null ? 0 : this.getShifts().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());
        result = 37 * result + (getEplAdminSchedule() == null ? 0 : this.getEplAdminSchedule().hashCode());
        
        return result;
    }

}
