/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Feb 17, 2009 10:51:32 AM by Hibernate Tools 3.2.0.beta8



/**
 * EplItemAuditHistoryDetailDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplItemAuditHistoryDetailDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields

    private static final long serialVersionUID = 1L;

    private Long eplId;
    private String colNm;
    private String oldValue;
    private String newValue;
    private String detailReason;
    private String detailEventCategory;

    private EplItemAuditHistoryDo eplItemAuditHistory;

    // Constructors

    /** default constructor */
    
    public EplItemAuditHistoryDetailDo() {
    }

    /** minimal constructor */
    
    public EplItemAuditHistoryDetailDo(Long eplId, String detailEventCategory) {
        this.eplId = eplId;
        this.detailEventCategory = detailEventCategory;

    }

    /** full constructor */
    
    public EplItemAuditHistoryDetailDo(Long eplId, String colNm, String oldValue, String newValue, String detailReason,
                                       String detailEventCategory, EplItemAuditHistoryDo eplItemAuditHistory) {
        this.eplId = eplId;
        this.colNm = colNm;
        this.oldValue = oldValue;
        this.newValue = newValue;
        this.detailReason = detailReason;
        this.detailEventCategory = detailEventCategory;

        this.eplItemAuditHistory = eplItemAuditHistory;
    }

    // Property accessors
    public Long getEplId() {
        return this.eplId;
    }

    public void setEplId(Long eplId) {
        this.eplId = eplId;
    }

    public String getColNm() {
        return this.colNm;
    }

    public void setColNm(String colNm) {
        this.colNm = colNm;
    }

    public String getOldValue() {
        return this.oldValue;
    }

    public void setOldValue(String oldValue) {
        this.oldValue = oldValue;
    }

    public String getNewValue() {
        return this.newValue;
    }

    public void setNewValue(String newValue) {
        this.newValue = newValue;
    }

    public String getDetailReason() {
        return this.detailReason;
    }

    public void setDetailReason(String detailReason) {
        this.detailReason = detailReason;
    }

    public String getDetailEventCategory() {
        return this.detailEventCategory;
    }

    public void setDetailEventCategory(String detailEventCategory) {
        this.detailEventCategory = detailEventCategory;
    }

    public EplItemAuditHistoryDo getEplItemAuditHistory() {
        return this.eplItemAuditHistory;
    }

    public void setEplItemAuditHistory(EplItemAuditHistoryDo eplItemAuditHistory) {
        this.eplItemAuditHistory = eplItemAuditHistory;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("colNm").append("='").append(getColNm()).append("' ");
        buffer.append("oldValue").append("='").append(getOldValue()).append("' ");
        buffer.append("newValue").append("='").append(getNewValue()).append("' ");
        buffer.append("detailReason").append("='").append(getDetailReason()).append("' ");
        buffer.append("detailEventCategory").append("='").append(getDetailEventCategory()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplItemAuditHistoryDetailDo)) {
            return false;
        }
        
        EplItemAuditHistoryDetailDo castOther = (EplItemAuditHistoryDetailDo) other;

        return ((this.getEplId() == castOther.getEplId()) || (this.getEplId() != null && castOther.getEplId() != null && this
            .getEplId().equals(castOther.getEplId())))
            && ((this.getColNm() == castOther.getColNm()) || (this.getColNm() != null
                && castOther.getColNm() != null && this.getColNm().equals(castOther.getColNm())))
            && ((this.getOldValue() == castOther.getOldValue()) || (this.getOldValue() != null
                && castOther.getOldValue() != null && this.getOldValue().equals(castOther.getOldValue())))
            && ((this.getNewValue() == castOther.getNewValue()) || (this.getNewValue() != null
                && castOther.getNewValue() != null && this.getNewValue().equals(castOther.getNewValue())))
            && ((this.getDetailReason() == castOther.getDetailReason()) || (this.getDetailReason() != null
                && castOther.getDetailReason() != null && this.getDetailReason().equals(castOther.getDetailReason())))
            && ((this.getDetailEventCategory() == castOther.getDetailEventCategory()) || (this.getDetailEventCategory() != null
                && castOther.getDetailEventCategory() != null && this.getDetailEventCategory().equals(
                    castOther.getDetailEventCategory())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())))
            && ((this.getEplItemAuditHistory() == castOther.getEplItemAuditHistory()) || (this.getEplItemAuditHistory() != null
                && castOther.getEplItemAuditHistory() != null && this.getEplItemAuditHistory().equals(
                    castOther.getEplItemAuditHistory())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getEplId() == null ? 0 : this.getEplId().hashCode());
        result = 37 * result + (getColNm() == null ? 0 : this.getColNm().hashCode());
        result = 37 * result + (getOldValue() == null ? 0 : this.getOldValue().hashCode());
        result = 37 * result + (getNewValue() == null ? 0 : this.getNewValue().hashCode());
        result = 37 * result + (getDetailReason() == null ? 0 : this.getDetailReason().hashCode());
        result = 37 * result + (getDetailEventCategory() == null ? 0 : this.getDetailEventCategory().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());
        result = 37 * result + (getEplItemAuditHistory() == null ? 0 : this.getEplItemAuditHistory().hashCode());
        
        return result;
    }

}
