/**
 * Source file created in 2011 by Southwest Research Institute
 * 
 * Generated Aug 24, 2011 10:37:08 AM by Hibernate Tools 3.2.4.GA
 */


package gov.va.med.pharmacy.peps.domain.common.model;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * EplMigrationControlDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplMigrationControlDo extends
        gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
        java.io.Serializable {

    public static final String USER_NAME = "userName";
    public static final String START_DATE = "startDtm";
    public static final String STOP_DATE = "stopDtm";
    public static final String THREAD_ID = "threadId";
    public static final String MIGRATION_STATUS = "migrationStatus";
    public static final String USER_NDC_FILE = "userNdcFile";
    public static final String USER_OI_FILE = "userOiFile";
    public static final String USER_PRODUCT_FILE = "userProductFile";

    private static final long serialVersionUID = 1L;

    private Long eplId;
    private String userName;
    private Date startDtm;
    private Date stopDtm;
    private Long threadId;
    private String migrationStatus;
    private String userNdcFile;
    private String userOiFile;
    private String userProductFile;
    private String createdBy;
    private Date createdDtm;
    private String lastModifiedBy;
    private Date lastModifiedDtm;
    private Set<EplMigrationFileDo> eplMigrationFiles = new HashSet<EplMigrationFileDo>(
            0);

    public EplMigrationControlDo() {
    }

    public EplMigrationControlDo(Long eplId, Date startDtm, Long threadId,
            String migrationStatus, String createdBy, Date createdDtm) {
        this.eplId = eplId;
        this.startDtm = startDtm;
        this.threadId = threadId;
        this.migrationStatus = migrationStatus;
        this.createdBy = createdBy;
        this.createdDtm = createdDtm;
    }

    public EplMigrationControlDo(Long eplId, String userName, Date startDtm,
            Date stopDtm, Long threadId, String migrationStatus,
            String userNdcFile, String userOiFile, String userProductFile,
            String createdBy, Date createdDtm, String lastModifiedBy,
            Date lastModifiedDtm, Set<EplMigrationFileDo> eplMigrationFiles) {
        this.eplId = eplId;
        this.userName = userName;
        this.startDtm = startDtm;
        this.stopDtm = stopDtm;
        this.threadId = threadId;
        this.migrationStatus = migrationStatus;
        this.userNdcFile = userNdcFile;
        this.userOiFile = userOiFile;
        this.userProductFile = userProductFile;
        this.createdBy = createdBy;
        this.createdDtm = createdDtm;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDtm = lastModifiedDtm;
        this.eplMigrationFiles = eplMigrationFiles;
    }

    public Long getEplId() {
        return this.eplId;
    }

    public void setEplId(Long eplId) {
        this.eplId = eplId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Date getStartDtm() {
        return this.startDtm;
    }

    public void setStartDtm(Date startDtm) {
        this.startDtm = startDtm;
    }

    public Date getStopDtm() {
        return this.stopDtm;
    }

    public void setStopDtm(Date stopDtm) {
        this.stopDtm = stopDtm;
    }

    public Long getThreadId() {
        return this.threadId;
    }

    public void setThreadId(Long threadId) {
        this.threadId = threadId;
    }

    public String getMigrationStatus() {
        return this.migrationStatus;
    }

    public void setMigrationStatus(String migrationStatus) {
        this.migrationStatus = migrationStatus;
    }

    public String getUserNdcFile() {
        return this.userNdcFile;
    }

    public void setUserNdcFile(String userNdcFile) {
        this.userNdcFile = userNdcFile;
    }

    public String getUserOiFile() {
        return this.userOiFile;
    }

    public void setUserOiFile(String userOiFile) {
        this.userOiFile = userOiFile;
    }

    public String getUserProductFile() {
        return this.userProductFile;
    }

    public void setUserProductFile(String userProductFile) {
        this.userProductFile = userProductFile;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }

    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDtm() {
        return this.lastModifiedDtm;
    }

    public void setLastModifiedDtm(Date lastModifiedDtm) {
        this.lastModifiedDtm = lastModifiedDtm;
    }

    public Set<EplMigrationFileDo> getEplMigrationFiles() {
        return this.eplMigrationFiles;
    }

    public void setEplMigrationFiles(Set<EplMigrationFileDo> eplMigrationFiles) {
        this.eplMigrationFiles = eplMigrationFiles;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@")
                .append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("userName").append("='").append(getUserName())
                .append("' ");
        buffer.append("startDtm").append("='").append(getStartDtm())
                .append("' ");
        buffer.append("stopDtm").append("='").append(getStopDtm()).append("' ");
        buffer.append("threadId").append("='").append(this.getThreadId())
                .append("' ");
        buffer.append("migrationStatus").append("='")
                .append(getMigrationStatus()).append("' ");
        buffer.append("userNdcFile").append("='").append(getUserNdcFile())
                .append("' ");
        buffer.append("userOiFile").append("='").append(getUserOiFile())
                .append("' ");
        buffer.append("userProductFile").append("='")
                .append(getUserProductFile()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy())
                .append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm())
                .append("' ");
        buffer.append("lastModifiedBy").append("='")
                .append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='")
                .append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplMigrationControlDo)) {
            return false;
        }

        EplMigrationControlDo castOther = (EplMigrationControlDo) other;

        return ((this.getUserName() == castOther.getUserName()) || (this
                .getUserName() != null && castOther.getUserName() != null && this
                .getUserName().equals(castOther.getUserName())))
                && ((this.getStartDtm() == castOther.getStartDtm()) || (this
                        .getStartDtm() != null
                        && castOther.getStartDtm() != null && this
                        .getStartDtm().equals(castOther.getStartDtm())))
                && ((this.getStopDtm() == castOther.getStopDtm()) || (this
                        .getStopDtm() != null && castOther.getStopDtm() != null && this
                        .getStopDtm().equals(castOther.getStopDtm())))
                && ((this.getThreadId() == castOther.getThreadId()) || (this
                        .getThreadId() != null
                        && castOther.getThreadId() != null && this
                        .getThreadId().equals(castOther.getThreadId())))
                && ((this.getMigrationStatus() == castOther
                        .getMigrationStatus()) || (this.getMigrationStatus() != null
                        && castOther.getMigrationStatus() != null && this
                        .getMigrationStatus().equals(
                                castOther.getMigrationStatus())))
                && ((this.getUserNdcFile() == castOther.getUserNdcFile()) || (this
                        .getUserNdcFile() != null
                        && castOther.getUserNdcFile() != null && this
                        .getUserNdcFile().equals(castOther.getUserNdcFile())))
                && ((this.getUserOiFile() == castOther.getUserOiFile()) || (this
                        .getUserOiFile() != null
                        && castOther.getUserOiFile() != null && this
                        .getUserOiFile().equals(castOther.getUserOiFile())))
                && ((this.getUserProductFile() == castOther
                        .getUserProductFile()) || (this.getUserProductFile() != null
                        && castOther.getUserProductFile() != null && this
                        .getUserProductFile().equals(
                                castOther.getUserProductFile())))
                && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
                        .getCreatedBy() != null
                        && castOther.getCreatedBy() != null && this
                        .getCreatedBy().equals(castOther.getCreatedBy())))
                && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this
                        .getCreatedDtm() != null
                        && castOther.getCreatedDtm() != null && this
                        .getCreatedDtm().equals(castOther.getCreatedDtm())))
                && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this
                        .getLastModifiedBy() != null
                        && castOther.getLastModifiedBy() != null && this
                        .getLastModifiedBy().equals(
                                castOther.getLastModifiedBy())))
                && ((this.getLastModifiedDtm() == castOther
                        .getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                        && castOther.getLastModifiedDtm() != null && this
                        .getLastModifiedDtm().equals(
                                castOther.getLastModifiedDtm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getUserName() == null ? 0 : this.getUserName().hashCode());
        result = 37 * result
                + (getStartDtm() == null ? 0 : this.getStartDtm().hashCode());
        result = 37 * result
                + (getStopDtm() == null ? 0 : this.getStopDtm().hashCode());
        result = 37 * result
                + (getThreadId() == null ? 0 : this.getThreadId().hashCode());
        result = 37
                * result
                + (getMigrationStatus() == null ? 0 : this.getMigrationStatus()
                        .hashCode());
        result = 37
                * result
                + (getUserNdcFile() == null ? 0 : this.getUserNdcFile()
                        .hashCode());
        result = 37
                * result
                + (getUserOiFile() == null ? 0 : this.getUserOiFile()
                        .hashCode());
        result = 37
                * result
                + (getUserProductFile() == null ? 0 : this.getUserProductFile()
                        .hashCode());
        result = 37 * result
                + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37
                * result
                + (getCreatedDtm() == null ? 0 : this.getCreatedDtm()
                        .hashCode());
        result = 37
                * result
                + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy()
                        .hashCode());
        result = 37
                * result
                + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm()
                        .hashCode());

        return result;
    }
}
