/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Aug 26, 2008 4:15:22 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * EplMedicationInstructionDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplMedicationInstructionDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {
    
    // Fields
    public static final String NAME = "medInstructionName";
    public static final String ITEM_STATUS = "itemStatus";
    public static final String REQUEST_STATUS = "requestStatus";
    public static final String INACTIVATION_DATE = "inactivationDate";
    public static final String EPL_ID = "eplId";
    
    private static final long serialVersionUID = 1L;

    private Long eplId;
    private String additionalInstruction;
    private String defaultAdminTimes;
    private String medInstructionExpansion;
    private Long frequencyInMinutes;
    private String instructions;
    private String intendedUse;
    private String medInstructionName;
    private String medInstructionOtherLangExp;
    private String plural;
    private String medInstructionSchedule;
    private String medInstructionSynonym;
    private Date inactivationDate;
    private String requestStatus;
    private String itemStatus;
    private String rejectReasonText;
    private String requestRejectReason;
    private Long revisionNumber;
    private Set<EplMedInstructWardDo> eplMedInstructWards = new HashSet<EplMedInstructWardDo>(0);
    private EplLocalMedRouteDo eplLocalMedRoute;

    // Constructors

    /** default constructor */
    
    public EplMedicationInstructionDo() {
    }

    /** minimal constructor */
    
    public EplMedicationInstructionDo(Long eplId, String defaultAdminTimes, String medInstructionExpansion,
                                      String medInstructionName, String requestStatus, String itemStatus,
                                      Long revisionNumber, String createdBy, Date createdDtm) {
        this.eplId = eplId;
        this.defaultAdminTimes = defaultAdminTimes;
        this.medInstructionExpansion = medInstructionExpansion;
        this.medInstructionName = medInstructionName;
        this.requestStatus = requestStatus;
        this.itemStatus = itemStatus;
        this.revisionNumber = revisionNumber;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */
    
    public EplMedicationInstructionDo(Long eplId, String additionalInstruction, String defaultAdminTimes,
                                      String medInstructionExpansion, Long frequencyInMinutes, String instructions,
                                      String intendedUse, String medInstructionName, String medInstructionOtherLangExp,
                                      String plural, String medInstructionSchedule, String medInstructionSynonym,
                                      Date inactivationDate, String requestStatus, String itemStatus,
                                      String rejectReasonText, String requestRejectReason, Long revisionNumber,
                                      String createdBy, Date createdDtm, String lastModifiedBy, Date lastModifiedDtm,
                                      Set<EplMedInstructWardDo> eplMedInstructWards, EplLocalMedRouteDo eplLocalMedRoute) {
        this.eplId = eplId;
        this.additionalInstruction = additionalInstruction;
        this.defaultAdminTimes = defaultAdminTimes;
        this.medInstructionExpansion = medInstructionExpansion;
        this.frequencyInMinutes = frequencyInMinutes;
        this.instructions = instructions;
        this.intendedUse = intendedUse;
        this.medInstructionName = medInstructionName;
        this.medInstructionOtherLangExp = medInstructionOtherLangExp;
        this.plural = plural;
        this.medInstructionSchedule = medInstructionSchedule;
        this.medInstructionSynonym = medInstructionSynonym;
        this.inactivationDate = inactivationDate;
        this.requestStatus = requestStatus;
        this.itemStatus = itemStatus;
        this.rejectReasonText = rejectReasonText;
        this.requestRejectReason = requestRejectReason;
        this.revisionNumber = revisionNumber;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplMedInstructWards = eplMedInstructWards;
        this.eplLocalMedRoute = eplLocalMedRoute;
    }

    // Property accessors
    public Long getEplId() {
        return this.eplId;
    }

    public void setEplId(Long eplId) {
        this.eplId = eplId;
    }

    public String getAdditionalInstruction() {
        return this.additionalInstruction;
    }

    public void setAdditionalInstruction(String additionalInstruction) {
        this.additionalInstruction = additionalInstruction;
    }

    public String getDefaultAdminTimes() {
        return this.defaultAdminTimes;
    }

    public void setDefaultAdminTimes(String defaultAdminTimes) {
        this.defaultAdminTimes = defaultAdminTimes;
    }

    public String getMedInstructionExpansion() {
        return this.medInstructionExpansion;
    }

    public void setMedInstructionExpansion(String medInstructionExpansion) {
        this.medInstructionExpansion = medInstructionExpansion;
    }

    public Long getFrequencyInMinutes() {
        return this.frequencyInMinutes;
    }

    public void setFrequencyInMinutes(Long frequencyInMinutes) {
        this.frequencyInMinutes = frequencyInMinutes;
    }

    public String getInstructions() {
        return this.instructions;
    }

    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }

    public String getIntendedUse() {
        return this.intendedUse;
    }

    public void setIntendedUse(String intendedUse) {
        this.intendedUse = intendedUse;
    }

    public String getMedInstructionName() {
        return this.medInstructionName;
    }

    public void setMedInstructionName(String medInstructionName) {
        this.medInstructionName = medInstructionName;
    }

    public String getMedInstructionOtherLangExp() {
        return this.medInstructionOtherLangExp;
    }

    public void setMedInstructionOtherLangExp(String medInstructionOtherLangExp) {
        this.medInstructionOtherLangExp = medInstructionOtherLangExp;
    }

    public String getPlural() {
        return this.plural;
    }

    public void setPlural(String plural) {
        this.plural = plural;
    }

    public String getMedInstructionSchedule() {
        return this.medInstructionSchedule;
    }

    public void setMedInstructionSchedule(String medInstructionSchedule) {
        this.medInstructionSchedule = medInstructionSchedule;
    }

    public String getMedInstructionSynonym() {
        return this.medInstructionSynonym;
    }

    public void setMedInstructionSynonym(String medInstructionSynonym) {
        this.medInstructionSynonym = medInstructionSynonym;
    }

    public Date getInactivationDate() {
        return this.inactivationDate;
    }

    public void setInactivationDate(Date inactivationDate) {
        this.inactivationDate = inactivationDate;
    }

    public String getRequestStatus() {
        return this.requestStatus;
    }

    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }

    public String getItemStatus() {
        return this.itemStatus;
    }

    public void setItemStatus(String itemStatus) {
        this.itemStatus = itemStatus;
    }

    public String getRejectReasonText() {
        return this.rejectReasonText;
    }

    public void setRejectReasonText(String rejectReasonText) {
        this.rejectReasonText = rejectReasonText;
    }

    public String getRequestRejectReason() {
        return this.requestRejectReason;
    }

    public void setRequestRejectReason(String requestRejectReason) {
        this.requestRejectReason = requestRejectReason;
    }

    public Long getRevisionNumber() {
        return this.revisionNumber;
    }

    public void setRevisionNumber(Long revisionNumber) {
        this.revisionNumber = revisionNumber;
    }

    public Set<EplMedInstructWardDo> getEplMedInstructWards() {
        return this.eplMedInstructWards;
    }

    public void setEplMedInstructWards(Set<EplMedInstructWardDo> eplMedInstructWards) {
        this.eplMedInstructWards = eplMedInstructWards;
    }

    public EplLocalMedRouteDo getEplLocalMedRoute() {
        return this.eplLocalMedRoute;
    }

    public void setEplLocalMedRoute(EplLocalMedRouteDo eplLocalMedRoute) {
        this.eplLocalMedRoute = eplLocalMedRoute;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("additionalInstruction").append("='").append(getAdditionalInstruction()).append("' ");
        buffer.append("defaultAdminTimes").append("='").append(getDefaultAdminTimes()).append("' ");
        buffer.append("medInstructionExpansion").append("='").append(getMedInstructionExpansion()).append("' ");
        buffer.append("frequencyInMinutes").append("='").append(getFrequencyInMinutes()).append("' ");
        buffer.append("instructions").append("='").append(getInstructions()).append("' ");
        buffer.append("intendedUse").append("='").append(getIntendedUse()).append("' ");
        buffer.append("medInstructionName").append("='").append(getMedInstructionName()).append("' ");
        buffer.append("medInstructionOtherLangExp").append("='").append(getMedInstructionOtherLangExp()).append("' ");
        buffer.append("plural").append("='").append(getPlural()).append("' ");
        buffer.append("medInstructionSchedule").append("='").append(getMedInstructionSchedule()).append("' ");
        buffer.append("medInstructionSynonym").append("='").append(getMedInstructionSynonym()).append("' ");
        buffer.append("inactivationDate").append("='").append(getInactivationDate()).append("' ");
        buffer.append("requestStatus").append("='").append(getRequestStatus()).append("' ");
        buffer.append("itemStatus").append("='").append(getItemStatus()).append("' ");
        buffer.append("rejectReasonText").append("='").append(getRejectReasonText()).append("' ");
        buffer.append("requestRejectReason").append("='").append(getRequestRejectReason()).append("' ");
        buffer.append("revisionNumber").append("='").append(getRevisionNumber()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplMedicationInstructionDo)) {
            return false;
        }
        
        EplMedicationInstructionDo castOther = (EplMedicationInstructionDo) other;

        return ((this.getEplId() == castOther.getEplId()) || (this.getEplId() != null && castOther.getEplId() != null && this
            .getEplId().equals(castOther.getEplId())))
            && ((this.getAdditionalInstruction() == castOther.getAdditionalInstruction()) || (this
                .getAdditionalInstruction() != null
                && castOther.getAdditionalInstruction() != null && this.getAdditionalInstruction().equals(
                    castOther.getAdditionalInstruction())))
            && ((this.getDefaultAdminTimes() == castOther.getDefaultAdminTimes()) || (this.getDefaultAdminTimes() != null
                && castOther.getDefaultAdminTimes() != null && this.getDefaultAdminTimes().equals(
                    castOther.getDefaultAdminTimes())))
            && ((this.getMedInstructionExpansion() == castOther.getMedInstructionExpansion()) || (this
                .getMedInstructionExpansion() != null
                && castOther.getMedInstructionExpansion() != null && this.getMedInstructionExpansion().equals(
                    castOther.getMedInstructionExpansion())))
            && ((this.getFrequencyInMinutes() == castOther.getFrequencyInMinutes()) || (this.getFrequencyInMinutes() != null
                && castOther.getFrequencyInMinutes() != null && this.getFrequencyInMinutes().equals(
                    castOther.getFrequencyInMinutes())))
            && ((this.getInstructions() == castOther.getInstructions()) || (this.getInstructions() != null
                && castOther.getInstructions() != null && this.getInstructions().equals(castOther.getInstructions())))
            && ((this.getIntendedUse() == castOther.getIntendedUse()) || (this.getIntendedUse() != null
                && castOther.getIntendedUse() != null && this.getIntendedUse().equals(castOther.getIntendedUse())))
            && ((this.getMedInstructionName() == castOther.getMedInstructionName()) || (this.getMedInstructionName() != null
                && castOther.getMedInstructionName() != null && this.getMedInstructionName().equals(
                    castOther.getMedInstructionName())))
            && ((this.getMedInstructionOtherLangExp() == castOther.getMedInstructionOtherLangExp()) || (this
                .getMedInstructionOtherLangExp() != null
                && castOther.getMedInstructionOtherLangExp() != null && this.getMedInstructionOtherLangExp().equals(
                    castOther.getMedInstructionOtherLangExp())))
            && ((this.getPlural() == castOther.getPlural()) || (this.getPlural() != null && castOther.getPlural() != null && this
                .getPlural().equals(castOther.getPlural())))
            && ((this.getMedInstructionSchedule() == castOther.getMedInstructionSchedule()) || (this
                .getMedInstructionSchedule() != null
                && castOther.getMedInstructionSchedule() != null && this.getMedInstructionSchedule().equals(
                    castOther.getMedInstructionSchedule())))
            && ((this.getMedInstructionSynonym() == castOther.getMedInstructionSynonym()) || (this
                .getMedInstructionSynonym() != null
                && castOther.getMedInstructionSynonym() != null && this.getMedInstructionSynonym().equals(
                    castOther.getMedInstructionSynonym())))
            && ((this.getInactivationDate() == castOther.getInactivationDate()) || (this.getInactivationDate() != null
                && castOther.getInactivationDate() != null && this.getInactivationDate().equals(
                    castOther.getInactivationDate())))
            && ((this.getRequestStatus() == castOther.getRequestStatus()) || (this.getRequestStatus() != null
                && castOther.getRequestStatus() != null && this.getRequestStatus().equals(castOther.getRequestStatus())))
            && ((this.getItemStatus() == castOther.getItemStatus()) || (this.getItemStatus() != null
                && castOther.getItemStatus() != null && this.getItemStatus().equals(castOther.getItemStatus())))
            && ((this.getRejectReasonText() == castOther.getRejectReasonText()) || (this.getRejectReasonText() != null
                && castOther.getRejectReasonText() != null && this.getRejectReasonText().equals(
                    castOther.getRejectReasonText())))
            && ((this.getRequestRejectReason() == castOther.getRequestRejectReason()) || (this.getRequestRejectReason() != null
                && castOther.getRequestRejectReason() != null && this.getRequestRejectReason().equals(
                    castOther.getRequestRejectReason())))
            && ((this.getRevisionNumber() == castOther.getRevisionNumber()) || (this.getRevisionNumber() != null
                && castOther.getRevisionNumber() != null && this.getRevisionNumber().equals(castOther.getRevisionNumber())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())))
            && ((this.getEplLocalMedRoute() == castOther.getEplLocalMedRoute()) || (this.getEplLocalMedRoute() != null
                && castOther.getEplLocalMedRoute() != null && this.getEplLocalMedRoute().equals(
                    castOther.getEplLocalMedRoute())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getEplId() == null ? 0 : this.getEplId().hashCode());
        result = 37 * result + (getAdditionalInstruction() == null ? 0 : this.getAdditionalInstruction().hashCode());
        result = 37 * result + (getDefaultAdminTimes() == null ? 0 : this.getDefaultAdminTimes().hashCode());
        result = 37 * result + (getMedInstructionExpansion() == null ? 0 : this.getMedInstructionExpansion().hashCode());
        result = 37 * result + (getFrequencyInMinutes() == null ? 0 : this.getFrequencyInMinutes().hashCode());
        result = 37 * result + (getInstructions() == null ? 0 : this.getInstructions().hashCode());
        result = 37 * result + (getIntendedUse() == null ? 0 : this.getIntendedUse().hashCode());
        result = 37 * result + (getMedInstructionName() == null ? 0 : this.getMedInstructionName().hashCode());
        result = 37 * result
            + (getMedInstructionOtherLangExp() == null ? 0 : this.getMedInstructionOtherLangExp().hashCode());
        result = 37 * result + (getPlural() == null ? 0 : this.getPlural().hashCode());
        result = 37 * result + (getMedInstructionSchedule() == null ? 0 : this.getMedInstructionSchedule().hashCode());
        result = 37 * result + (getMedInstructionSynonym() == null ? 0 : this.getMedInstructionSynonym().hashCode());
        result = 37 * result + (getInactivationDate() == null ? 0 : this.getInactivationDate().hashCode());
        result = 37 * result + (getRequestStatus() == null ? 0 : this.getRequestStatus().hashCode());
        result = 37 * result + (getItemStatus() == null ? 0 : this.getItemStatus().hashCode());
        result = 37 * result + (getRejectReasonText() == null ? 0 : this.getRejectReasonText().hashCode());
        result = 37 * result + (getRequestRejectReason() == null ? 0 : this.getRequestRejectReason().hashCode());
        result = 37 * result + (getRevisionNumber() == null ? 0 : this.getRevisionNumber().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());

        result = 37 * result + (getEplLocalMedRoute() == null ? 0 : this.getEplLocalMedRoute().hashCode());
        
        return result;
    }

}
