/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


/**
 * EplMultiTextDoKey generated by hbm2java
 * @hibernate.class
 */
public class EplMultiTextDoKey implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    // Fields

    private Long vadfOwnerIdFk;
    private Long vadfIdFk;
    private String text;

    // Constructors

    /** default constructor */
    
    public EplMultiTextDoKey() {
    }

    /** full constructor */
    
    public EplMultiTextDoKey(Long vadfOwnerIdFk, Long vadfIdFk, String text) {
        this.vadfOwnerIdFk = vadfOwnerIdFk;
        this.vadfIdFk = vadfIdFk;
        this.text = text;
    }

    // Property accessors
    public Long getVadfOwnerIdFk() {
        return this.vadfOwnerIdFk;
    }

    public void setVadfOwnerIdFk(Long vadfOwnerIdFk) {
        this.vadfOwnerIdFk = vadfOwnerIdFk;
    }

    public Long getVadfIdFk() {
        return this.vadfIdFk;
    }

    public void setVadfIdFk(Long vadfIdFk) {
        this.vadfIdFk = vadfIdFk;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplMultiTextDoKey)) {
            return false;
        }
        
        EplMultiTextDoKey castOther = (EplMultiTextDoKey) other;

        return ((this.getVadfOwnerIdFk() == castOther.getVadfOwnerIdFk()) || (this.getVadfOwnerIdFk() != null
            && castOther.getVadfOwnerIdFk() != null && this.getVadfOwnerIdFk().equals(castOther.getVadfOwnerIdFk())))
            && ((this.getVadfIdFk() == castOther.getVadfIdFk()) || (this.getVadfIdFk() != null
                && castOther.getVadfIdFk() != null && this.getVadfIdFk().equals(castOther.getVadfIdFk())))
            && ((this.getText() == castOther.getText()) || (this.getText() != null && castOther.getText() != null && this
                .getText().equals(castOther.getText())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getVadfOwnerIdFk() == null ? 0 : this.getVadfOwnerIdFk().hashCode());
        result = 37 * result + (getVadfIdFk() == null ? 0 : this.getVadfIdFk().hashCode());
        result = 37 * result + (getText() == null ? 0 : this.getText().hashCode());
       
        return result;
    }

}
