/**
 * Source file created in 2011 by Southwest Research Institute
 * 
 * Generated Aug 24, 2011 10:37:08 AM by Hibernate Tools 3.2.4.GA
 */


package gov.va.med.pharmacy.peps.domain.common.model;


import java.util.Date;


/**
 * EplMigrationErrorDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplMigrationErrorDo extends
        gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
        java.io.Serializable {

    public static final String FILE_ID = "fileId";
    public static final String MIGRATION_UNIQUE_VALUE = "migrationUniqueValue";
    public static final String MIGRATION_ROW_ID = "migrationRowId";
    public static final String MIGRATION_MULT_ROW_ID = "migrationMultRowId";
    public static final String MIGRATION_FIELD_VALUE = "migrationFieldValue";
    public static final String MIGRATION_FIELD_NAME = "migrationFieldName";
    public static final String MIGRATION_MULT_FIELD_NAME = "migrationMultFieldName";
    public static final String DETAILED_ERROR_TEXT = "detailedErrorText";

    private static final long serialVersionUID = 1L;

    private Double fileId;
    private String migrationUniqueValue;
    private String migrationRowId;
    private String migrationMultRowId;
    private String migrationFieldValue;
    private String migrationFieldName;
    private String migrationMultFieldName;
    private String detailedErrorText;
    private Date processedDtm;
    private String createdBy;
    private Date createdDtm;
    private String lastModifiedBy;
    private Date lastModifiedDtm;

    public EplMigrationErrorDo() {
    }

    public EplMigrationErrorDo(Double fileId, Long migrationRowId,
            String migrationFieldName, String detailedErrorText,
            Date processedDtm, String createdBy, Date createdDtm) {
        this.fileId = fileId;
        this.detailedErrorText = detailedErrorText;
        this.processedDtm = processedDtm;
        this.createdBy = createdBy;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    public EplMigrationErrorDo(Double fileId, String migrationUniqueValue,
            String migrationRowId, String migrationMultRowId,
            String migrationFieldValue, String migrationFieldName,
            String migrationMultFieldName, String detailedErrorText,
            Date processedDtm, String createdBy, Date createdDtm,
            String lastModifiedBy, Date lastModifiedDtm) {
        this.fileId = fileId;
        this.migrationUniqueValue = migrationUniqueValue;
        this.migrationRowId = migrationRowId;
        this.migrationMultRowId = migrationMultRowId;
        this.migrationFieldValue = migrationFieldValue;
        this.migrationFieldName = migrationFieldName;
        this.migrationMultFieldName = migrationMultFieldName;
        this.detailedErrorText = detailedErrorText;
        this.processedDtm = processedDtm;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
    }

    public String getMigrationUniqueValue() {
        return migrationUniqueValue;
    }

    public void setMigrationUniqueValue(String migrationUniqueValue) {
        this.migrationUniqueValue = migrationUniqueValue;
    }

    public String getMigrationFieldValue() {
        return migrationFieldValue;
    }

    public void setMigrationFieldValue(String migrationFieldValue) {
        this.migrationFieldValue = migrationFieldValue;
    }

    public Double getFileId() {
        return this.fileId;
    }

    public void setFileId(Double fileId) {
        this.fileId = fileId;
    }

    public String getMigrationRowId() {
        return this.migrationRowId;
    }

    public void setMigrationRowId(String migrationRowId) {
        this.migrationRowId = migrationRowId;
    }

    public String getMigrationMultRowId() {
        return this.migrationMultRowId;
    }

    public void setMigrationMultRowId(String migrationMultRowId) {
        this.migrationMultRowId = migrationMultRowId;
    }

    public String getMigrationFieldName() {
        return this.migrationFieldName;
    }

    public void setMigrationFieldName(String migrationFieldName) {
        this.migrationFieldName = migrationFieldName;
    }

    public String getMigrationMultFieldName() {
        return this.migrationMultFieldName;
    }

    public void setMigrationMultFieldName(String migrationMultFieldName) {
        this.migrationMultFieldName = migrationMultFieldName;
    }

    public String getDetailedErrorText() {
        return this.detailedErrorText;
    }

    public void setDetailedErrorText(String detailedErrorText) {
        this.detailedErrorText = detailedErrorText;
    }

    public Date getProcessedDtm() {
        return this.processedDtm;
    }

    public void setProcessedDtm(Date processedDtm) {
        this.processedDtm = processedDtm;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }

    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDtm() {
        return this.lastModifiedDtm;
    }

    public void setLastModifiedDtm(Date lastModifiedDtm) {
        this.lastModifiedDtm = lastModifiedDtm;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@")
                .append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("fileId").append("='").append(getFileId()).append("' ");
        buffer.append("migrationUniqueValue").append("='")
                .append(getMigrationUniqueValue()).append("' ");
        buffer.append("migrationRowId").append("='")
                .append(getMigrationRowId()).append("' ");
        buffer.append("migrationMultRowId").append("='")
                .append(getMigrationMultRowId()).append("' ");
        buffer.append("migrationFieldValue").append("='")
                .append(getMigrationFieldValue()).append("' ");
        buffer.append("migrationFieldName").append("='")
                .append(this.getMigrationFieldName()).append("' ");
        buffer.append("migrationMultFieldName").append("='")
                .append(getMigrationMultFieldName()).append("' ");
        buffer.append("detailedErrorText").append("='")
                .append(getDetailedErrorText()).append("' ");
        buffer.append("processedDtm").append("='").append(getProcessedDtm())
                .append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy())
                .append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm())
                .append("' ");
        buffer.append("lastModifiedBy").append("='")
                .append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='")
                .append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplMigrationErrorDo)) {
            return false;
        }

        EplMigrationErrorDo castOther = (EplMigrationErrorDo) other;

        return ((this.getFileId() == castOther.getFileId()) || (this
                .getFileId() != null && castOther.getFileId() != null && this
                .getFileId().equals(castOther.getFileId())))
                && ((this.getMigrationUniqueValue() == castOther
                        .getMigrationUniqueValue()) || (this
                        .getMigrationUniqueValue() != null
                        && castOther.getMigrationUniqueValue() != null && this
                        .getMigrationUniqueValue().equals(
                                castOther.getMigrationUniqueValue())))
                && ((this.getMigrationRowId() == castOther.getMigrationRowId()) || (this
                        .getMigrationRowId() != null
                        && castOther.getMigrationRowId() != null && this
                        .getMigrationRowId().equals(
                                castOther.getMigrationRowId())))
                && ((this.getMigrationMultRowId() == castOther
                        .getMigrationMultRowId()) || (this
                        .getMigrationMultRowId() != null
                        && castOther.getMigrationMultRowId() != null && this
                        .getMigrationMultRowId().equals(
                                castOther.getMigrationMultRowId())))
                && ((this.getMigrationFieldName() == castOther
                        .getMigrationFieldName()) || (this
                        .getMigrationFieldName() != null
                        && castOther.getMigrationFieldName() != null && this
                        .getMigrationFieldName().equals(
                                castOther.getMigrationFieldName())))
                && ((this.getMigrationFieldValue() == castOther
                        .getMigrationFieldValue()) || (this
                        .getMigrationFieldValue() != null
                        && castOther.getMigrationFieldValue() != null && this
                        .getMigrationFieldValue().equals(
                                castOther.getMigrationFieldValue())))
                && ((this.getMigrationMultFieldName() == castOther
                        .getMigrationMultFieldName()) || (this
                        .getMigrationMultFieldName() != null
                        && castOther.getMigrationMultFieldName() != null && this
                        .getMigrationMultFieldName().equals(
                                castOther.getMigrationMultFieldName())))
                && ((this.getDetailedErrorText() == castOther
                        .getDetailedErrorText()) || (this
                        .getDetailedErrorText() != null
                        && castOther.getDetailedErrorText() != null && this
                        .getDetailedErrorText().equals(
                                castOther.getDetailedErrorText())))
                && ((this.getProcessedDtm() == castOther.getProcessedDtm()) || (this
                        .getProcessedDtm() != null
                        && castOther.getProcessedDtm() != null && this
                        .getProcessedDtm().equals(castOther.getProcessedDtm())))
                && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
                        .getCreatedBy() != null
                        && castOther.getCreatedBy() != null && this
                        .getCreatedBy().equals(castOther.getCreatedBy())))
                && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this
                        .getCreatedDtm() != null
                        && castOther.getCreatedDtm() != null && this
                        .getCreatedDtm().equals(castOther.getCreatedDtm())))
                && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this
                        .getLastModifiedBy() != null
                        && castOther.getLastModifiedBy() != null && this
                        .getLastModifiedBy().equals(
                                castOther.getLastModifiedBy())))
                && ((this.getLastModifiedDtm() == castOther
                        .getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                        && castOther.getLastModifiedDtm() != null && this
                        .getLastModifiedDtm().equals(
                                castOther.getLastModifiedDtm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getFileId() == null ? 0 : this.getFileId().hashCode());
        result = 37
                * result
                + (getMigrationUniqueValue() == null ? 0 : this
                        .getMigrationUniqueValue().hashCode());
        result = 37
                * result
                + (getMigrationRowId() == null ? 0 : this.getMigrationRowId()
                        .hashCode());
        result = 37
                * result
                + (getMigrationMultRowId() == null ? 0 : this
                        .getMigrationMultRowId().hashCode());
        result = 37
                * result
                + (getMigrationFieldValue() == null ? 0 : this
                        .getMigrationFieldValue().hashCode());
        result = 37
                * result
                + (getMigrationFieldName() == null ? 0 : this
                        .getMigrationFieldName().hashCode());
        result = 37
                * result
                + (getMigrationMultFieldName() == null ? 0 : this
                        .getMigrationMultFieldName().hashCode());
        result = 37
                * result
                + (getDetailedErrorText() == null ? 0 : this
                        .getDetailedErrorText().hashCode());
        result = 37
                * result
                + (getProcessedDtm() == null ? 0 : this.getProcessedDtm()
                        .hashCode());
        result = 37 * result
                + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37
                * result
                + (getCreatedDtm() == null ? 0 : this.getCreatedDtm()
                        .hashCode());
        result = 37
                * result
                + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy()
                        .hashCode());
        result = 37
                * result
                + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm()
                        .hashCode());

        return result;
    }
}
