/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated May 14, 2008 2:06:44 PM by Hibernate Tools 3.2.0.beta8



/**
 * EplNotificationStatusDoKey generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplNotificationStatusDoKey implements java.io.Serializable {

    // Fields

    private static final long serialVersionUID = 1L;
    
    private Long notificationIdFk;
    private Long userIdFk;

    // Constructors

    /** default constructor */

    public EplNotificationStatusDoKey() {
    }

    /** full constructor */

    public EplNotificationStatusDoKey(Long notificationIdFk, Long userIdFk) {
        this.notificationIdFk = notificationIdFk;
        this.userIdFk = userIdFk;
    }

    // Property accessors
    public Long getNotificationIdFk() {
        return this.notificationIdFk;
    }

    public void setNotificationIdFk(Long notificationIdFk) {
        this.notificationIdFk = notificationIdFk;
    }

    public Long getUserIdFk() {
        return this.userIdFk;
    }

    public void setUserIdFk(Long userIdFk) {
        this.userIdFk = userIdFk;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("notificationIdFk").append("='").append(getNotificationIdFk()).append("' ");
        buffer.append("userIdFk").append("='").append(getUserIdFk()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }
    
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplNotificationStatusDoKey)) {
            return false;
        }

        EplNotificationStatusDoKey castOther = (EplNotificationStatusDoKey) other;

        return ((this.getNotificationIdFk() == castOther.getNotificationIdFk()) || (this.getNotificationIdFk() != null
            && castOther.getNotificationIdFk() != null && this.getNotificationIdFk().equals(castOther.getNotificationIdFk())))
            && ((this.getUserIdFk() == castOther.getUserIdFk()) || (this.getUserIdFk() != null
                && castOther.getUserIdFk() != null && this.getUserIdFk().equals(castOther.getUserIdFk())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNotificationIdFk() == null ? 0 : this.getNotificationIdFk().hashCode());
        result = 37 * result + (getUserIdFk() == null ? 0 : this.getUserIdFk().hashCode());

        return result;
    }

}
