package gov.va.med.pharmacy.peps.domain.common.model;
// Generated Dec 20, 2011 1:14:38 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * EplNationalSettingDo generated by hbm2java
 * 
 * 
 * @hibernate.class
 */
 public class EplNationalSettingDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements java.io.Serializable {

    // Fields
    public static final String ID = "id";
    public static final String KEY_NAME = "keyName";
    public static final String STRING_VALUE = "stringValue";
    public static final String INTEGER_VALUE = "integerValue";
    public static final String DECIMAL_VALUE = "decimalValue";
    public static final String BOOL_VALUE = "booleanValue";
    public static final String DATE_VALUE = "dateValue";
    
    private static final long serialVersionUID = 1L; 

    private Long id;
    private String keyName;
    private String stringValue;
    private Long integerValue;
    private Long decimalValue;
    private Long booleanValue;
    private Date dateValue;
    private String createdBy;
    private Date createdDtm;
    private String lastModifiedBy;
    private Date lastModifiedDtm;

    public EplNationalSettingDo() {
    }

	
    public EplNationalSettingDo(Long id, String keyName, String createdBy, Date createdDtm) {
        this.id = id;
        this.keyName = keyName;
        this.createdBy = createdBy;
        this.createdDtm = createdDtm;
    }

    public EplNationalSettingDo(Long id, String keyName, String stringValue, Long integerValue, Long decimalValue, 
                                Long booleanValue, Date dateValue, String createdBy, Date createdDtm, String lastModifiedBy, 
                                Date lastModifiedDtm) {
       this.id = id;
       this.keyName = keyName;
       this.stringValue = stringValue;
       this.integerValue = integerValue;
       this.decimalValue = decimalValue;
       this.booleanValue = booleanValue;
       this.dateValue = dateValue;
       this.createdBy = createdBy;
       this.createdDtm = createdDtm;
       this.lastModifiedBy = lastModifiedBy;
       this.lastModifiedDtm = lastModifiedDtm;
    }
    
    /**
     * 
     * @return id
     */
    public Long getId() {
        return this.id;
    }
    
    /**
     * 
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }
    
    /**
     * 
     * @return keyName
     */
    public String getKeyName() {
        return this.keyName;
    }
    
    /**
     * 
     * @param keyName
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName;
    }
    
    /**
     * 
     * @return stringValue
     */
    public String getStringValue() {
        return this.stringValue;
    }
    
    /**
     * 
     * @param stringValue
     */
    public void setStringValue(String stringValue) {
        this.stringValue = stringValue;
    }
    
    /**
     * 
     * @return integerValue
     */
    public Long getIntegerValue() {
        return this.integerValue;
    }
    
    /**
     * 
     * @param integerValue
     */
    public void setIntegerValue(Long integerValue) {
        this.integerValue = integerValue;
    }
    
    /**
     * 
     * @return decimalValue
     */
    public Long getDecimalValue() {
        return this.decimalValue;
    }
    
    /**
     * 
     * @param decimalValue
     */
    public void setDecimalValue(Long decimalValue) {
        this.decimalValue = decimalValue;
    }
    
    /**
     * 
     * @return booleanValue
     */
    public Long getBooleanValue() {
        return this.booleanValue;
    }
    
    /**
     * 
     * @param booleanValue
     */
    public void setBooleanValue(Long booleanValue) {
        this.booleanValue = booleanValue;
    }
    
    /**
     * 
     * @return dateValue
     */
    public Date getDateValue() {
        return this.dateValue;
    }
    
    /**
     * 
     * @param dateValue
     */
    public void setDateValue(Date dateValue) {
        this.dateValue = dateValue;
    }
    
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    
    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }
    
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }
    
    public Date getLastModifiedDtm() {
        return this.lastModifiedDtm;
    }
    
    public void setLastModifiedDtm(Date lastModifiedDtm) {
        this.lastModifiedDtm = lastModifiedDtm;
    }


    /* (non-Javadoc)
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#toString()
     */
    @Override
    public String toString() {
        return "EplNationalSettingDo [id=" + id + ", keyName=" + keyName + ", stringValue=" + 
               stringValue + ", integerValue=" + integerValue + ", decimalValue=" + 
               decimalValue + ", booleanValue=" + booleanValue + ", dateValue=" + dateValue + 
               ", createdBy=" + createdBy + ", createdDtm=" + createdDtm + ", lastModifiedBy=" + 
               lastModifiedBy + ", lastModifiedDtm=" + lastModifiedDtm + "]";
    }


    /* (non-Javadoc)
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((booleanValue == null) ? 0 : booleanValue.hashCode());
        result = prime * result + ((createdBy == null) ? 0 : createdBy.hashCode());
        result = prime * result + ((createdDtm == null) ? 0 : createdDtm.hashCode());
        result = prime * result + ((dateValue == null) ? 0 : dateValue.hashCode());
        result = prime * result + ((decimalValue == null) ? 0 : decimalValue.hashCode());
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((integerValue == null) ? 0 : integerValue.hashCode());
        result = prime * result + ((keyName == null) ? 0 : keyName.hashCode());
        result = prime * result + ((lastModifiedBy == null) ? 0 : lastModifiedBy.hashCode());
        result = prime * result + ((lastModifiedDtm == null) ? 0 : lastModifiedDtm.hashCode());
        result = prime * result + ((stringValue == null) ? 0 : stringValue.hashCode());
        return result;
    }


    /* (non-Javadoc)
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!super.equals(obj))
            return false;
        if (getClass() != obj.getClass())
            return false;
        EplNationalSettingDo other = (EplNationalSettingDo) obj;
        if (booleanValue == null) {
            if (other.booleanValue != null)
                return false;
        } else if (!booleanValue.equals(other.booleanValue))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        } else if (!createdBy.equals(other.createdBy))
            return false;
        if (createdDtm == null) {
            if (other.createdDtm != null)
                return false;
        } else if (!createdDtm.equals(other.createdDtm))
            return false;
        if (dateValue == null) {
            if (other.dateValue != null)
                return false;
        } else if (!dateValue.equals(other.dateValue))
            return false;
        if (decimalValue == null) {
            if (other.decimalValue != null)
                return false;
        } else if (!decimalValue.equals(other.decimalValue))
            return false;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (integerValue == null) {
            if (other.integerValue != null)
                return false;
        } else if (!integerValue.equals(other.integerValue))
            return false;
        if (keyName == null) {
            if (other.keyName != null)
                return false;
        } else if (!keyName.equals(other.keyName))
            return false;
        if (lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        } else if (!lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (lastModifiedDtm == null) {
            if (other.lastModifiedDtm != null)
                return false;
        } else if (!lastModifiedDtm.equals(other.lastModifiedDtm))
            return false;
        if (stringValue == null) {
            if (other.stringValue != null)
                return false;
        } else if (!stringValue.equals(other.stringValue))
            return false;
        return true;
    }
}


