/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Jan 8, 2009 3:09:37 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


/**
 * EplOiAdminSchedAssocDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplOiAdminSchedAssocDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String ORDERABLE_ITEM_EPL_ID = "eplOrderableItem.eplId";
    public static final String EPL_ADMIN_SCHEDULE = "eplAdminSchedule";
    
    private static final long serialVersionUID = 1L;

    private EplOiAdminSchedAssocDoKey key;
    private String defaultScheduleYn;
    private EplAdminScheduleDo eplAdminSchedule;
    private EplOrderableItemDo eplOrderableItem;

    // Constructors

    /** default constructor */
    
    public EplOiAdminSchedAssocDo() {
    }

    /** minimal constructor */
    
    public EplOiAdminSchedAssocDo(EplOiAdminSchedAssocDoKey key, String createdBy, Date createdDtm) {
        this.key = key;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */
    
    public EplOiAdminSchedAssocDo(EplOiAdminSchedAssocDoKey key, String defaultScheduleYn, String createdBy,
                                  Date createdDtm, String lastModifiedBy, Date lastModifiedDtm,
                                  EplAdminScheduleDo eplAdminSchedule, EplOrderableItemDo eplOrderableItem) {
        this.key = key;
        this.defaultScheduleYn = defaultScheduleYn;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplAdminSchedule = eplAdminSchedule;
        this.eplOrderableItem = eplOrderableItem;
    }

    // Property accessors
    public EplOiAdminSchedAssocDoKey getKey() {
        return this.key;
    }

    public void setKey(EplOiAdminSchedAssocDoKey key) {
        this.key = key;
    }

    public String getDefaultScheduleYn() {
        return this.defaultScheduleYn;
    }

    public void setDefaultScheduleYn(String defaultScheduleYn) {
        this.defaultScheduleYn = defaultScheduleYn;
    }
    
    public EplAdminScheduleDo getEplAdminSchedule() {
        return this.eplAdminSchedule;
    }

    public void setEplAdminSchedule(EplAdminScheduleDo eplAdminSchedule) {
        this.eplAdminSchedule = eplAdminSchedule;
    }

    public EplOrderableItemDo getEplOrderableItem() {
        return this.eplOrderableItem;
    }

    public void setEplOrderableItem(EplOrderableItemDo eplOrderableItem) {
        this.eplOrderableItem = eplOrderableItem;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("defaultScheduleYn").append("='").append(getDefaultScheduleYn()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplOiAdminSchedAssocDo)) {
            return false;
        }

        EplOiAdminSchedAssocDo castOther = (EplOiAdminSchedAssocDo) other;

        return ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this
            .getKey().equals(castOther.getKey())))
            && ((this.getDefaultScheduleYn() == castOther.getDefaultScheduleYn()) || (this.getDefaultScheduleYn() != null
                && castOther.getDefaultScheduleYn() != null && this.getDefaultScheduleYn().equals(
                    castOther.getDefaultScheduleYn())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
        result = 37 * result + (getDefaultScheduleYn() == null ? 0 : this.getDefaultScheduleYn().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());

        return result;
    }

}
