/**
 * Source file created in 2008 by Southwest Research Institute
 */



package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Jan 8, 2009 3:09:37 PM by Hibernate Tools 3.2.0.betimport java.math.Long;



/**
 * EplOiAdminSchedAssocDoKey generated by hbm2java
 */
public class EplOiAdminSchedAssocDoKey implements java.io.Serializable {

    // Fields

    private static final long serialVersionUID = 1L;
    
    private Long eplIdAdminSchedFk;
    private Long eplIdOiFk;

    // Constructors

    /** default constructor */
    
    public EplOiAdminSchedAssocDoKey() {
    }

    /** full constructor */
    
    public EplOiAdminSchedAssocDoKey(Long eplIdAdminSchedFk, Long eplIdOiFk) {
        this.eplIdAdminSchedFk = eplIdAdminSchedFk;
        this.eplIdOiFk = eplIdOiFk;
    }

    // Property accessors
    public Long getEplIdAdminSchedFk() {
        return this.eplIdAdminSchedFk;
    }

    public void setEplIdAdminSchedFk(Long eplIdAdminSchedFk) {
        this.eplIdAdminSchedFk = eplIdAdminSchedFk;
    }

    public Long getEplIdOiFk() {
        return this.eplIdOiFk;
    }

    public void setEplIdOiFk(Long eplIdOiFk) {
        this.eplIdOiFk = eplIdOiFk;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplOiAdminSchedAssocDoKey)) {
            return false;
        }

        EplOiAdminSchedAssocDoKey castOther = (EplOiAdminSchedAssocDoKey) other;

        return ((this.getEplIdAdminSchedFk() == castOther.getEplIdAdminSchedFk()) || (this.getEplIdAdminSchedFk() != null
            && castOther.getEplIdAdminSchedFk() != null && this.getEplIdAdminSchedFk().equals(
                castOther.getEplIdAdminSchedFk())))
            && ((this.getEplIdOiFk() == castOther.getEplIdOiFk()) || (this.getEplIdOiFk() != null
                && castOther.getEplIdOiFk() != null && this.getEplIdOiFk().equals(castOther.getEplIdOiFk())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getEplIdAdminSchedFk() == null ? 0 : this.getEplIdAdminSchedFk().hashCode());
        result = 37 * result + (getEplIdOiFk() == null ? 0 : this.getEplIdOiFk().hashCode());
        
        return result;
    }

}
