/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Feb 3, 2009 2:10:07 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * EplOiScheduleTypeDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplOiScheduleTypeDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String CODE = "code";
    
    private static final long serialVersionUID = 1L;

    private Long id;
    private String code;
    private String oiScheduleType;
    private Set<EplOrderableItemDo> eplOrderableItems = new HashSet<EplOrderableItemDo>(0);

    // Constructors

    /** default constructor */
    
    public EplOiScheduleTypeDo() {
    }

    /** minimal constructor */
    
    public EplOiScheduleTypeDo(Long id, String code, String oiScheduleType, String createdBy, Date createdDtm) {
        this.id = id;
        this.code = code;
        this.oiScheduleType = oiScheduleType;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */
    
    public EplOiScheduleTypeDo(Long id, String code, String oiScheduleType, String createdBy, Date createdDtm,
                               String lastModifiedBy, Date lastModifiedDtm, Set<EplOrderableItemDo> eplOrderableItems) {
        this.id = id;
        this.code = code;
        this.oiScheduleType = oiScheduleType;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplOrderableItems = eplOrderableItems;
    }

    // Property accessors
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getOiScheduleType() {
        return this.oiScheduleType;
    }

    public void setOiScheduleType(String oiScheduleType) {
        this.oiScheduleType = oiScheduleType;
    }

    public Set<EplOrderableItemDo> getEplOrderableItems() {
        return this.eplOrderableItems;
    }

    public void setEplOrderableItems(Set<EplOrderableItemDo> eplOrderableItems) {
        this.eplOrderableItems = eplOrderableItems;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("code").append("='").append(getCode()).append("' ");
        buffer.append("oiScheduleType").append("='").append(getOiScheduleType()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplOiScheduleTypeDo)) {
            return false;
        }
        
        EplOiScheduleTypeDo castOther = (EplOiScheduleTypeDo) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId()
            .equals(castOther.getId())))
            && ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null && this
                .getCode().equals(castOther.getCode())))
            && ((this.getOiScheduleType() == castOther.getOiScheduleType()) || (this.getOiScheduleType() != null
                && castOther.getOiScheduleType() != null && this.getOiScheduleType().equals(castOther.getOiScheduleType())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
        result = 37 * result + (getOiScheduleType() == null ? 0 : this.getOiScheduleType().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());

        return result;
    }

}
