/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Jun 13, 2008 3:16:08 PM by Hibernate Tools 3.2.0.beta8



/**
 * EplOiMedRouteAssocDoKey generated by hbm2java
 * @hibernate.class
 */
public class EplOiMedRouteAssocDoKey implements java.io.Serializable {

    // Fields
    
    private static final long serialVersionUID = 1L;

    private Long eplIdOiFk;
    private Long medRouteIdFk;

    // Constructors

    /** default constructor */

    public EplOiMedRouteAssocDoKey() {
    }

    /** full constructor */

    public EplOiMedRouteAssocDoKey(Long eplIdOiFk, Long medRouteIdFk) {
        this.eplIdOiFk = eplIdOiFk;
        this.medRouteIdFk = medRouteIdFk;
    }

    // Property accessors
    public Long getEplIdOiFk() {
        return this.eplIdOiFk;
    }

    public void setEplIdOiFk(Long eplIdOiFk) {
        this.eplIdOiFk = eplIdOiFk;
    }

    public Long getMedRouteIdFk() {
        return this.medRouteIdFk;
    }

    public void setMedRouteIdFk(Long medRouteIdFk) {
        this.medRouteIdFk = medRouteIdFk;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplOiMedRouteAssocDoKey)) {
            return false;
        }

        EplOiMedRouteAssocDoKey castOther = (EplOiMedRouteAssocDoKey) other;

        return ((this.getEplIdOiFk() == castOther.getEplIdOiFk()) || (this.getEplIdOiFk() != null
            && castOther.getEplIdOiFk() != null && this.getEplIdOiFk().equals(castOther.getEplIdOiFk())))
            && ((this.getMedRouteIdFk() == castOther.getMedRouteIdFk()) || (this.getMedRouteIdFk() != null
                && castOther.getMedRouteIdFk() != null && this.getMedRouteIdFk().equals(castOther.getMedRouteIdFk())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getEplIdOiFk() == null ? 0 : this.getEplIdOiFk().hashCode());
        result = 37 * result + (getMedRouteIdFk() == null ? 0 : this.getMedRouteIdFk().hashCode());

        return result;
    }

}
