/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


import java.util.Date;


/**
 * EplOiMedRouteAssocDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplOiMedRouteAssocDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String EPL_LOCAL_MED_ROUTE = "eplLocalMedRoute";
    public static final String ORDERABLE_ITEM_EPL_ID = "eplOrderableItem.eplId";
    
    private static final long serialVersionUID = 1L;

    private EplOiMedRouteAssocDoKey key;
    private String defaultYn;
    private EplLocalMedRouteDo eplLocalMedRoute;
    private EplOrderableItemDo eplOrderableItem;

    // Constructors

    /** default constructor */

    public EplOiMedRouteAssocDo() {
    }

    /** minimal constructor */

    public EplOiMedRouteAssocDo(EplOiMedRouteAssocDoKey key, String defaultYn, String createdBy, Date createdDtm) {
        this.key = key;
        this.defaultYn = defaultYn;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */

    public EplOiMedRouteAssocDo(EplOiMedRouteAssocDoKey key, String defaultYn, String createdBy, Date createdDtm,
                                String lastModifiedBy, Date lastModifiedDtm, EplLocalMedRouteDo eplLocalMedRoute,
                                EplOrderableItemDo eplOrderableItem) {
        this.key = key;
        this.defaultYn = defaultYn;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplLocalMedRoute = eplLocalMedRoute;
        this.eplOrderableItem = eplOrderableItem;
    }

    // Property accessors
    public EplOiMedRouteAssocDoKey getKey() {
        return this.key;
    }

    public void setKey(EplOiMedRouteAssocDoKey key) {
        this.key = key;
    }

    public String getDefaultYn() {
        return this.defaultYn;
    }

    public void setDefaultYn(String defaultYn) {
        this.defaultYn = defaultYn;
    }

    public EplLocalMedRouteDo getEplLocalMedRoute() {
        return this.eplLocalMedRoute;
    }

    public void setEplLocalMedRoute(EplLocalMedRouteDo eplLocalMedRoute) {
        this.eplLocalMedRoute = eplLocalMedRoute;
    }

    public EplOrderableItemDo getEplOrderableItem() {
        return this.eplOrderableItem;
    }

    public void setEplOrderableItem(EplOrderableItemDo eplOrderableItem) {
        this.eplOrderableItem = eplOrderableItem;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("defaultYn").append("='").append(getDefaultYn()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplOiMedRouteAssocDo)) {
            return false;
        }

        EplOiMedRouteAssocDo castOther = (EplOiMedRouteAssocDo) other;

        return ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this
            .getKey().equals(castOther.getKey())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
        

        return result;
    }

}
