/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Mar 11, 2008 2:09:00 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


/**
 * EplPartialSaveMgtDo generated by hbm2java
 * @hibernate.class
 */
public class EplPartialSaveMgtDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String ORDERABLE_ITEM_EPL_ID = "eplOrderableItem.eplId";
    public static final String PRODUCT_EPL_ID = "eplProduct.eplId";
    public static final String NDC_EPL_ID = "eplNdc.eplId";
    
    private static final long serialVersionUID = 1L;

    private Long id;
    private String entityType;
    private String requestType;
    private String fileName;
    private Long itemRevisionNumber;
    private String comments;
    private EplOrderableItemDo eplOrderableItem;
    private EplProductDo eplProduct;
    private EplNdcDo eplNdc;

    // Constructors

    /** default constructor */

    public EplPartialSaveMgtDo() {
    }

    /** minimal constructor */

    public EplPartialSaveMgtDo(Long id, String entityType, String requestType, String fileName, Long itemRevisionNumber,
                               String createdBy, Date createdDtm) {
        this.id = id;
        this.entityType = entityType;
        this.requestType = requestType;
        this.fileName = fileName;
        this.itemRevisionNumber = itemRevisionNumber;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */

    public EplPartialSaveMgtDo(Long id, String entityType, String requestType, String fileName, Long itemRevisionNumber,
                               String comments, String createdBy, Date createdDtm, String lastModifiedBy,
                               Date lastModifiedDtm, EplOrderableItemDo eplOrderableItem, EplProductDo eplProduct,
                               EplNdcDo eplNdc) {
        this.id = id;
        this.entityType = entityType;
        this.requestType = requestType;
        this.fileName = fileName;
        this.itemRevisionNumber = itemRevisionNumber;
        this.comments = comments;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplOrderableItem = eplOrderableItem;
        this.eplProduct = eplProduct;
        this.eplNdc = eplNdc;
    }

    // Property accessors
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEntityType() {
        return this.entityType;
    }

    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    public String getRequestType() {
        return this.requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getItemRevisionNumber() {
        return this.itemRevisionNumber;
    }

    public void setItemRevisionNumber(Long itemRevisionNumber) {
        this.itemRevisionNumber = itemRevisionNumber;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public EplOrderableItemDo getEplOrderableItem() {
        return this.eplOrderableItem;
    }

    public void setEplOrderableItem(EplOrderableItemDo eplOrderableItem) {
        this.eplOrderableItem = eplOrderableItem;
    }

    public EplProductDo getEplProduct() {
        return this.eplProduct;
    }

    public void setEplProduct(EplProductDo eplProduct) {
        this.eplProduct = eplProduct;
    }

    public EplNdcDo getEplNdc() {
        return this.eplNdc;
    }

    public void setEplNdc(EplNdcDo eplNdc) {
        this.eplNdc = eplNdc;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("entityType").append("='").append(getEntityType()).append("' ");
        buffer.append("requestType").append("='").append(getRequestType()).append("' ");
        buffer.append("fileName").append("='").append(getFileName()).append("' ");
        buffer.append("itemRevisionNumber").append("='").append(getItemRevisionNumber()).append("' ");
        buffer.append("comments").append("='").append(getComments()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplPartialSaveMgtDo)) {
            return false;
        }

        EplPartialSaveMgtDo castOther = (EplPartialSaveMgtDo) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId()
            .equals(castOther.getId())))
            && ((this.getEntityType() == castOther.getEntityType()) || (this.getEntityType() != null
                && castOther.getEntityType() != null && this.getEntityType().equals(castOther.getEntityType())))
            && ((this.getRequestType() == castOther.getRequestType()) || (this.getRequestType() != null
                && castOther.getRequestType() != null && this.getRequestType().equals(castOther.getRequestType())))
            && ((this.getFileName() == castOther.getFileName()) || (this.getFileName() != null
                && castOther.getFileName() != null && this.getFileName().equals(castOther.getFileName())))
            && ((this.getItemRevisionNumber() == castOther.getItemRevisionNumber()) || (this.getItemRevisionNumber() != null
                && castOther.getItemRevisionNumber() != null && this.getItemRevisionNumber().equals(
                    castOther.getItemRevisionNumber())))
            && ((this.getComments() == castOther.getComments()) || (this.getComments() != null
                && castOther.getComments() != null && this.getComments().equals(castOther.getComments())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())))
            && ((this.getEplOrderableItem() == castOther.getEplOrderableItem()) || (this.getEplOrderableItem() != null
                && castOther.getEplOrderableItem() != null && this.getEplOrderableItem().equals(
                    castOther.getEplOrderableItem())))
            && ((this.getEplProduct() == castOther.getEplProduct()) || (this.getEplProduct() != null
                && castOther.getEplProduct() != null && this.getEplProduct().equals(castOther.getEplProduct())))
            && ((this.getEplNdc() == castOther.getEplNdc()) || (this.getEplNdc() != null && castOther.getEplNdc() != null && this
                .getEplNdc().equals(castOther.getEplNdc())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getEntityType() == null ? 0 : this.getEntityType().hashCode());
        result = 37 * result + (getRequestType() == null ? 0 : this.getRequestType().hashCode());
        result = 37 * result + (getFileName() == null ? 0 : this.getFileName().hashCode());
        result = 37 * result + (getItemRevisionNumber() == null ? 0 : this.getItemRevisionNumber().hashCode());
        result = 37 * result + (getComments() == null ? 0 : this.getComments().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());
        result = 37 * result + (getEplOrderableItem() == null ? 0 : this.getEplOrderableItem().hashCode());
        result = 37 * result + (getEplProduct() == null ? 0 : this.getEplProduct().hashCode());
        result = 37 * result + (getEplNdc() == null ? 0 : this.getEplNdc().hashCode());

        return result;
    }

}
