/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Feb 17, 2009 10:26:30 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


/**
 * EplProductLabDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplProductLabDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements java.io.Serializable {

    // Fields
    public static final String ORDER_ENTRY = "labDisplayOrderEntry";
    public static final String FINISH_AN_ORDER = "labDisplayFinishAnOrder";
    public static final String ADMINISTRATION = "labDisplayAdministration";
    
    private static final long serialVersionUID = 1L;

    private Long id;
    private String labDisplayOrderEntry;
    private String labDisplayFinishAnOrder;
    private String labDisplayAdministration;
    private EplProductDo eplProduct;

    // Constructors

    /** default constructor */
    
    public EplProductLabDo() {
    }

    /** minimal constructor */
    
    public EplProductLabDo(Long id, String labDisplayOrderEntry, String labDisplayFinishAnOrder,
                           String labDisplayAdministration, String createdBy, Date createdDtm) {
        this.id = id;
        this.labDisplayOrderEntry = labDisplayOrderEntry;
        this.labDisplayFinishAnOrder = labDisplayFinishAnOrder;
        this.labDisplayAdministration = labDisplayAdministration;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */
    
    public EplProductLabDo(Long id, String labDisplayOrderEntry, String labDisplayFinishAnOrder,
                           String labDisplayAdministration, String createdBy, Date createdDtm, String lastModifiedBy,
                           Date lastModifiedDtm, EplProductDo eplProduct) {
        this.id = id;
        this.labDisplayOrderEntry = labDisplayOrderEntry;
        this.labDisplayFinishAnOrder = labDisplayFinishAnOrder;
        this.labDisplayAdministration = labDisplayAdministration;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplProduct = eplProduct;
    }

    // Property accessors
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLabDisplayOrderEntry() {
        return this.labDisplayOrderEntry;
    }

    public void setLabDisplayOrderEntry(String labDisplayOrderEntry) {
        this.labDisplayOrderEntry = labDisplayOrderEntry;
    }

    public String getLabDisplayFinishAnOrder() {
        return this.labDisplayFinishAnOrder;
    }

    public void setLabDisplayFinishAnOrder(String labDisplayFinishAnOrder) {
        this.labDisplayFinishAnOrder = labDisplayFinishAnOrder;
    }

    public String getLabDisplayAdministration() {
        return this.labDisplayAdministration;
    }

    public void setLabDisplayAdministration(String labDisplayAdministration) {
        this.labDisplayAdministration = labDisplayAdministration;
    }

    public EplProductDo getEplProduct() {
        return this.eplProduct;
    }

    public void setEplProduct(EplProductDo eplProduct) {
        this.eplProduct = eplProduct;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("labDisplayOrderEntry").append("='").append(getLabDisplayOrderEntry()).append("' ");
        buffer.append("labDisplayFinishAnOrder").append("='").append(getLabDisplayFinishAnOrder()).append("' ");
        buffer.append("labDisplayAdministration").append("='").append(getLabDisplayAdministration()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplProductLabDo)) {
            return false;
        }

        EplProductLabDo castOther = (EplProductLabDo) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId()
            .equals(castOther.getId())))
            && ((this.getLabDisplayOrderEntry() == castOther.getLabDisplayOrderEntry()) || (this.getLabDisplayOrderEntry() != null
                && castOther.getLabDisplayOrderEntry() != null && this.getLabDisplayOrderEntry().equals(
                    castOther.getLabDisplayOrderEntry())))
            && ((this.getLabDisplayFinishAnOrder() == castOther.getLabDisplayFinishAnOrder()) || (this
                .getLabDisplayFinishAnOrder() != null
                && castOther.getLabDisplayFinishAnOrder() != null && this.getLabDisplayFinishAnOrder().equals(
                    castOther.getLabDisplayFinishAnOrder())))
            && ((this.getLabDisplayAdministration() == castOther.getLabDisplayAdministration()) || (this
                .getLabDisplayAdministration() != null
                && castOther.getLabDisplayAdministration() != null && this.getLabDisplayAdministration().equals(
                    castOther.getLabDisplayAdministration())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())))
            && ((this.getEplProduct() == castOther.getEplProduct()) || (this.getEplProduct() != null
                && castOther.getEplProduct() != null && this.getEplProduct().equals(castOther.getEplProduct())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getLabDisplayOrderEntry() == null ? 0 : this.getLabDisplayOrderEntry().hashCode());
        result = 37 * result + (getLabDisplayFinishAnOrder() == null ? 0 : this.getLabDisplayFinishAnOrder().hashCode());
        result = 37 * result + (getLabDisplayAdministration() == null ? 0 : this.getLabDisplayAdministration().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());
        result = 37 * result + (getEplProduct() == null ? 0 : this.getEplProduct().hashCode());
        
        return result;
    }

}
