/*
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Mar 4, 2009 2:59:16 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


/**
 * EplProdWarnLabelLAssocDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplProdWarnLabelLAssocDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String EPL_ID_WARN_LABEL_FK = "key.eplIdWarnLabelFk";
    public static final String EPL_WARNING_LABEL = "eplWarnLabel";
    
    private static final long serialVersionUID = 1L;

    private EplProdWarnLabelLAssocDoKey key;
    private EplWarnLabelDo eplWarnLabel;
    private EplProductDo eplProduct;

    // Constructors

    /** default constructor */

    public EplProdWarnLabelLAssocDo() {
    }

    /** minimal constructor */

    public EplProdWarnLabelLAssocDo(EplProdWarnLabelLAssocDoKey key, String createdBy, Date createdDtm) {
        this.key = key;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */

    public EplProdWarnLabelLAssocDo(EplProdWarnLabelLAssocDoKey key, String createdBy, Date createdDtm,
                                    String lastModifiedBy, Date lastModifiedDtm, EplWarnLabelDo eplWarnLabel,
                                    EplProductDo eplProduct) {
        this.key = key;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplWarnLabel = eplWarnLabel;
        this.eplProduct = eplProduct;
    }

    // Property accessors
    public EplProdWarnLabelLAssocDoKey getKey() {
        return this.key;
    }

    public void setKey(EplProdWarnLabelLAssocDoKey key) {
        this.key = key;
    }

    public EplWarnLabelDo getEplWarnLabel() {
        return this.eplWarnLabel;
    }

    public void setEplWarnLabel(EplWarnLabelDo eplWarnLabel) {
        this.eplWarnLabel = eplWarnLabel;
    }

    public EplProductDo getEplProduct() {
        return this.eplProduct;
    }

    public void setEplProduct(EplProductDo eplProduct) {
        this.eplProduct = eplProduct;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplProdWarnLabelLAssocDo)) {
            return false;
        }

        EplProdWarnLabelLAssocDo castOther = (EplProdWarnLabelLAssocDo) other;

        return ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this
            .getKey().equals(castOther.getKey())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());

        return result;
    }

}
