/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated May 4, 2009 4:24:25 PM by Hibernate Tools 3.2.0.beta8

/**
 * EplProdSpecHandlingAssocDoKey generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplProdSpecHandlingAssocDoKey implements java.io.Serializable {

    // Fields
    private static final long serialVersionUID = 1L;
    private Long eplIdProdFk;
    private Long eplIdSpecHandlingFk;

    // Constructors

    /** default constructor */

    public EplProdSpecHandlingAssocDoKey() {
    }

    /** full constructor */

    public EplProdSpecHandlingAssocDoKey(Long eplIdProdFk, Long eplIdSpecHandlingFk) {
        this.eplIdProdFk = eplIdProdFk;
        this.eplIdSpecHandlingFk = eplIdSpecHandlingFk;
    }

    // Property accessors
    public Long getEplIdProdFk() {
        return this.eplIdProdFk;
    }

    public void setEplIdProdFk(Long eplIdProdFk) {
        this.eplIdProdFk = eplIdProdFk;
    }

    public Long getEplIdSpecHandlingFk() {
        return this.eplIdSpecHandlingFk;
    }

    public void setEplIdSpecHandlingFk(Long eplIdSpecHandlingFk) {
        this.eplIdSpecHandlingFk = eplIdSpecHandlingFk;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplProdSpecHandlingAssocDoKey)) {
            return false;
        }
        
        EplProdSpecHandlingAssocDoKey castOther = (EplProdSpecHandlingAssocDoKey) other;

        return ((this.getEplIdProdFk() == castOther.getEplIdProdFk()) || (this.getEplIdProdFk() != null
            && castOther.getEplIdProdFk() != null && this.getEplIdProdFk().equals(castOther.getEplIdProdFk())))
            && ((this.getEplIdSpecHandlingFk() == castOther.getEplIdSpecHandlingFk()) || (this.getEplIdSpecHandlingFk() != null
                && castOther.getEplIdSpecHandlingFk() != null && this.getEplIdSpecHandlingFk().equals(
                    castOther.getEplIdSpecHandlingFk())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getEplIdProdFk() == null ? 0 : this.getEplIdProdFk().hashCode());
        result = 37 * result + (getEplIdSpecHandlingFk() == null ? 0 : this.getEplIdSpecHandlingFk().hashCode());
        
        return result;
    }

}
