/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Jan 8, 2009 3:09:37 PM by Hibernate Tools 3.2.0.beta8



/**
 * EplProdDrugTextLAssocDoKey generated by hbm2java
 */
public class EplProdDrugTextLAssocDoKey implements java.io.Serializable {

    // Fields

    private static final long serialVersionUID = 1L;
    
    private Long eplIdProdFk;
    private Long drugTextIdFk;

    // Constructors

    /** default constructor */
    
    public EplProdDrugTextLAssocDoKey() {
    }

    /** full constructor */
    
    public EplProdDrugTextLAssocDoKey(Long eplIdProdFk, Long drugTextIdFk) {
        this.eplIdProdFk = eplIdProdFk;
        this.drugTextIdFk = drugTextIdFk;
    }

    // Property accessors
    public Long getEplIdProdFk() {
        return this.eplIdProdFk;
    }

    public void setEplIdProdFk(Long eplIdProdFk) {
        this.eplIdProdFk = eplIdProdFk;
    }

    public Long getDrugTextIdFk() {
        return this.drugTextIdFk;
    }

    public void setDrugTextIdFk(Long drugTextIdFk) {
        this.drugTextIdFk = drugTextIdFk;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplProdDrugTextLAssocDoKey)) {
            return false;
        }

        EplProdDrugTextLAssocDoKey castOther = (EplProdDrugTextLAssocDoKey) other;

        return ((this.getEplIdProdFk() == castOther.getEplIdProdFk()) || (this.getEplIdProdFk() != null
            && castOther.getEplIdProdFk() != null && this.getEplIdProdFk().equals(castOther.getEplIdProdFk())))
            && ((this.getDrugTextIdFk() == castOther.getDrugTextIdFk()) || (this.getDrugTextIdFk() != null
                && castOther.getDrugTextIdFk() != null && this.getDrugTextIdFk().equals(castOther.getDrugTextIdFk())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getEplIdProdFk() == null ? 0 : this.getEplIdProdFk().hashCode());
        result = 37 * result + (getDrugTextIdFk() == null ? 0 : this.getDrugTextIdFk().hashCode());
        
        return result;
    }

}
