/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Nov 11, 2008 4:25:29 PM by Hibernate Tools 3.2.0.beta8

import java.sql.Blob;
import java.util.Date;


/**
 * EplRequestDetailDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplRequestDetailDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String EPL_REQUEST = "eplRequest";
    public static final String EPL_REQUEST_ID = "eplRequest.id";
    
    private static final long serialVersionUID = 1L;

    private Long id;
    private String editAtLocalYn;
    private String modificationReason;
    private String siteName;
    private String status;
    private String rejectReasonText;
    private String requestRejectReason;
    private String note;
    private String lastReviewerName;
    private String requesterName;
    private String requestToModifyYn;
    private Blob difference;
    private EplRequestDo eplRequest;

    // Constructors

    /** default constructor */
    
    public EplRequestDetailDo() {
    }

    /** minimal constructor */
    
    public EplRequestDetailDo(Long id, String siteName, String status, Blob difference, String createdBy, Date createdDtm) {
        this.id = id;
        this.siteName = siteName;
        this.status = status;
        this.difference = difference;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */
    
    public EplRequestDetailDo(Long id, String editAtLocalYn, String modificationReason, String siteName, String status,
                              String rejectReasonText, String requestRejectReason, String note, String lastReviewerName,
                              String requesterName, String requestToModifyYn, Blob difference, String createdBy,
                              Date createdDtm, String lastModifiedBy, Date lastModifiedDtm, EplRequestDo eplRequest) {
        this.id = id;
        this.editAtLocalYn = editAtLocalYn;
        this.modificationReason = modificationReason;
        this.siteName = siteName;
        this.status = status;
        this.rejectReasonText = rejectReasonText;
        this.requestRejectReason = requestRejectReason;
        this.note = note;
        this.lastReviewerName = lastReviewerName;
        this.requesterName = requesterName;
        this.requestToModifyYn = requestToModifyYn;
        this.difference = difference;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplRequest = eplRequest;
    }

    // Property accessors
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEditAtLocalYn() {
        return this.editAtLocalYn;
    }

    public void setEditAtLocalYn(String editAtLocalYn) {
        this.editAtLocalYn = editAtLocalYn;
    }

    public String getModificationReason() {
        return this.modificationReason;
    }

    public void setModificationReason(String modificationReason) {
        this.modificationReason = modificationReason;
    }

    public String getSiteName() {
        return this.siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRejectReasonText() {
        return this.rejectReasonText;
    }

    public void setRejectReasonText(String rejectReasonText) {
        this.rejectReasonText = rejectReasonText;
    }

    public String getRequestRejectReason() {
        return this.requestRejectReason;
    }

    public void setRequestRejectReason(String requestRejectReason) {
        this.requestRejectReason = requestRejectReason;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getLastReviewerName() {
        return this.lastReviewerName;
    }

    public void setLastReviewerName(String lastReviewerName) {
        this.lastReviewerName = lastReviewerName;
    }

    public String getRequesterName() {
        return this.requesterName;
    }

    public void setRequesterName(String requesterName) {
        this.requesterName = requesterName;
    }

    public String getRequestToModifyYn() {
        return this.requestToModifyYn;
    }

    public void setRequestToModifyYn(String requestToModifyYn) {
        this.requestToModifyYn = requestToModifyYn;
    }

    public Blob getDifference() {
        return this.difference;
    }

    public void setDifference(Blob difference) {
        this.difference = difference;
    }

    public EplRequestDo getEplRequest() {
        return this.eplRequest;
    }

    public void setEplRequest(EplRequestDo eplRequest) {
        this.eplRequest = eplRequest;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("editAtLocalYn").append("='").append(getEditAtLocalYn()).append("' ");
        buffer.append("modificationReason").append("='").append(getModificationReason()).append("' ");
        buffer.append("siteName").append("='").append(getSiteName()).append("' ");
        buffer.append("status").append("='").append(getStatus()).append("' ");
        buffer.append("rejectReasonText").append("='").append(getRejectReasonText()).append("' ");
        buffer.append("requestRejectReason").append("='").append(getRequestRejectReason()).append("' ");
        buffer.append("note").append("='").append(getNote()).append("' ");
        buffer.append("lastReviewerName").append("='").append(getLastReviewerName()).append("' ");
        buffer.append("requesterName").append("='").append(getRequesterName()).append("' ");
        buffer.append("requestToModifyYn").append("='").append(getRequestToModifyYn()).append("' ");
        buffer.append("difference").append("='").append(getDifference()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplRequestDetailDo)) {
            return false;
        }

        EplRequestDetailDo castOther = (EplRequestDetailDo) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId()
            .equals(castOther.getId())))
            && ((this.getEditAtLocalYn() == castOther.getEditAtLocalYn()) || (this.getEditAtLocalYn() != null
                && castOther.getEditAtLocalYn() != null && this.getEditAtLocalYn().equals(castOther.getEditAtLocalYn())))
            && ((this.getModificationReason() == castOther.getModificationReason()) || (this.getModificationReason() != null
                && castOther.getModificationReason() != null && this.getModificationReason().equals(
                    castOther.getModificationReason())))
            && ((this.getSiteName() == castOther.getSiteName()) || (this.getSiteName() != null
                && castOther.getSiteName() != null && this.getSiteName().equals(castOther.getSiteName())))
            && ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null && castOther.getStatus() != null && this
                .getStatus().equals(castOther.getStatus())))
            && ((this.getRejectReasonText() == castOther.getRejectReasonText()) || (this.getRejectReasonText() != null
                && castOther.getRejectReasonText() != null && this.getRejectReasonText().equals(
                    castOther.getRejectReasonText())))
            && ((this.getRequestRejectReason() == castOther.getRequestRejectReason()) || (this.getRequestRejectReason() != null
                && castOther.getRequestRejectReason() != null && this.getRequestRejectReason().equals(
                    castOther.getRequestRejectReason())))
            && ((this.getNote() == castOther.getNote()) || (this.getNote() != null && castOther.getNote() != null && this
                .getNote().equals(castOther.getNote())))
            && ((this.getLastReviewerName() == castOther.getLastReviewerName()) || (this.getLastReviewerName() != null
                && castOther.getLastReviewerName() != null && this.getLastReviewerName().equals(
                    castOther.getLastReviewerName())))
            && ((this.getRequesterName() == castOther.getRequesterName()) || (this.getRequesterName() != null
                && castOther.getRequesterName() != null && this.getRequesterName().equals(castOther.getRequesterName())))
            && ((this.getRequestToModifyYn() == castOther.getRequestToModifyYn()) || (this.getRequestToModifyYn() != null
                && castOther.getRequestToModifyYn() != null && this.getRequestToModifyYn().equals(
                    castOther.getRequestToModifyYn())))
            && ((this.getDifference() == castOther.getDifference()) || (this.getDifference() != null
                && castOther.getDifference() != null && this.getDifference().equals(castOther.getDifference())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())))
            && ((this.getEplRequest() == castOther.getEplRequest()) || (this.getEplRequest() != null
                && castOther.getEplRequest() != null && this.getEplRequest().equals(castOther.getEplRequest())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getEditAtLocalYn() == null ? 0 : this.getEditAtLocalYn().hashCode());
        result = 37 * result + (getModificationReason() == null ? 0 : this.getModificationReason().hashCode());
        result = 37 * result + (getSiteName() == null ? 0 : this.getSiteName().hashCode());
        result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
        result = 37 * result + (getRejectReasonText() == null ? 0 : this.getRejectReasonText().hashCode());
        result = 37 * result + (getRequestRejectReason() == null ? 0 : this.getRequestRejectReason().hashCode());
        result = 37 * result + (getNote() == null ? 0 : this.getNote().hashCode());
        result = 37 * result + (getLastReviewerName() == null ? 0 : this.getLastReviewerName().hashCode());
        result = 37 * result + (getRequesterName() == null ? 0 : this.getRequesterName().hashCode());
        result = 37 * result + (getRequestToModifyYn() == null ? 0 : this.getRequestToModifyYn().hashCode());
        result = 37 * result + (getDifference() == null ? 0 : this.getDifference().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());
        result = 37 * result + (getEplRequest() == null ? 0 : this.getEplRequest().hashCode());
        
        return result;
    }

}
