/* Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Jun 24, 2008 3:37:34 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.Set;


/**
 * EplStandardMedRouteDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplStandardMedRouteDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String NAME = "standardMedRouteName";
    public static final String ITEM_STATUS = "itemStatus";
    public static final String REQUEST_STATUS = "requestStatus";
    public static final String INACTIVATION_DATE = "inactivationDate";
    public static final String EPL_ID = "eplId";

    private static final long serialVersionUID = 1L;

    private Long eplId;
    private String vuid;
    private String masterEntryForVuid;
    private String standardMedRouteName;
    private String firstDatabankMedRoute;
    private Date inactivationDate;
    private String requestStatus;
    private String itemStatus;
    private String rejectReasonText;
    private String requestRejectReason;
    private Long revisionNumber;
    private EplStandardMedRouteDo eplStandardMedRoute;

    // Constructors

    /** default constructor */

    public EplStandardMedRouteDo() {
    }

    /** minimal constructor */

    public EplStandardMedRouteDo(Long eplId, String vuid, String masterEntryForVuid,
                                 String standardMedRouteName, String firstDatabankMedRoute,
                                 String requestStatus, String itemStatus, Long revisionNumber, String createdBy,
                                 Date createdDtm) {
        this.eplId = eplId;
        this.vuid = vuid;
        this.masterEntryForVuid = masterEntryForVuid;
        this.standardMedRouteName = standardMedRouteName;
        this.firstDatabankMedRoute = firstDatabankMedRoute;
        this.requestStatus = requestStatus;
        this.itemStatus = itemStatus;
        this.revisionNumber = revisionNumber;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */

    public EplStandardMedRouteDo(Long eplId, String vuid, String standardMedRouteName, String masterEntryForVuid,
                                 String firstDatabankMedRoute,
                                 Date inactivationDate, String requestStatus, String itemStatus, String rejectReasonText,
                                 String requestRejectReason, Long revisionNumber, String createdBy, Date createdDtm,
                                 String lastModifiedBy, Date lastModifiedDtm, Set<EplOiMedRouteAssocDo> eplOiMedRouteAssocs,
                                 Set<EplDfMedRtDfAssocDo> eplDfMedRtDfAssocs) {
        this.eplId = eplId;
        this.vuid = vuid;
        this.masterEntryForVuid = masterEntryForVuid;
        this.standardMedRouteName = standardMedRouteName;
        this.firstDatabankMedRoute = firstDatabankMedRoute;
        this.inactivationDate = inactivationDate;
        this.requestStatus = requestStatus;
        this.itemStatus = itemStatus;
        this.rejectReasonText = rejectReasonText;
        this.requestRejectReason = requestRejectReason;
        this.revisionNumber = revisionNumber;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
    }

    // Property accessors
    public Long getEplId() {
        return this.eplId;
    }

    public void setEplId(Long eplId) {
        this.eplId = eplId;
    }

    public String getVuid() {
        return this.vuid;
    }

    public void setMasterEntryForVuid(String masterEntryForVuid) {
        this.masterEntryForVuid = masterEntryForVuid;
    }

    public String getMasterEntryForVuid() {
        return this.masterEntryForVuid;
    }

    public void setVuid(String vuid) {
        this.vuid = vuid;
    }

    
    public String getStandardMedRouteName() {
        return this.standardMedRouteName;
    }

    public void setStandardMedRouteName(String standardMedRouteName) {
        this.standardMedRouteName = standardMedRouteName;
    }

    public String getFirstDatabankMedRoute() {
        return this.firstDatabankMedRoute;
    }

    public void setFirstDatabankMedRoute(String firstDatabankMedRoute) {
        this.firstDatabankMedRoute = firstDatabankMedRoute;
    }

    public Date getInactivationDate() {
        return this.inactivationDate;
    }

    public void setInactivationDate(Date inactivationDate) {
        this.inactivationDate = inactivationDate;
    }

    public String getRequestStatus() {
        return this.requestStatus;
    }

    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }

    public String getItemStatus() {
        return this.itemStatus;
    }

    public void setItemStatus(String itemStatus) {
        this.itemStatus = itemStatus;
    }

    public String getRejectReasonText() {
        return this.rejectReasonText;
    }

    public void setRejectReasonText(String rejectReasonText) {
        this.rejectReasonText = rejectReasonText;
    }

    public String getRequestRejectReason() {
        return this.requestRejectReason;
    }

    public void setRequestRejectReason(String requestRejectReason) {
        this.requestRejectReason = requestRejectReason;
    }

    public Long getRevisionNumber() {
        return this.revisionNumber;
    }

    public void setRevisionNumber(Long revisionNumber) {
        this.revisionNumber = revisionNumber;
    }

  
    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode()));
        buffer.append(" [vuid='").append(getVuid());
        buffer.append("' standardMedRouteName='").append(getStandardMedRouteName());
        buffer.append("' masterEntryForVuid='").append(getMasterEntryForVuid());
        buffer.append("' firstDatabankMedRoute='").append(getFirstDatabankMedRoute());
        buffer.append("' inactivationDate='").append(getInactivationDate());
        buffer.append("' requestStatus='").append(getRequestStatus());
        buffer.append("' itemStatus='").append(getItemStatus());
        buffer.append("' rejectReasonText='").append(getRejectReasonText());
        buffer.append("' requestRejectReason='").append(getRequestRejectReason());
        buffer.append("' revisionNumber='").append(getRevisionNumber());
        buffer.append("' createdBy='").append(getCreatedBy());
        buffer.append("' createdDtm='").append(getCreatedDtm());
        buffer.append("' lastModifiedBy='").append(getLastModifiedBy());
        buffer.append("' lastModifiedDtm='").append(getLastModifiedDtm());
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplStandardMedRouteDo)) {
            return false;
        }

        EplStandardMedRouteDo castOther = (EplStandardMedRouteDo) other;

        return ((this.getEplId() == castOther.getEplId()) || (this.getEplId() != null && castOther.getEplId() != null && this
            .getEplId().equals(castOther.getEplId())))
            && ((this.getVuid() == castOther.getVuid()) || (this.getVuid() != null && castOther.getVuid() != null && this
                .getVuid().equals(castOther.getVuid())))
            && ((this.getStandardMedRouteName() == castOther.getStandardMedRouteName()) || (this.getStandardMedRouteName() != null
                && castOther.getStandardMedRouteName() != null && this.getStandardMedRouteName().equals(
                    castOther.getStandardMedRouteName())))
            && ((this.getFirstDatabankMedRoute() == castOther.getFirstDatabankMedRoute()) || (this
                .getFirstDatabankMedRoute() != null
                && castOther.getFirstDatabankMedRoute() != null && this.getFirstDatabankMedRoute().equals(
                    castOther.getFirstDatabankMedRoute())))
            && ((this.getMasterEntryForVuid() == castOther.getMasterEntryForVuid()) || (this
                .getMasterEntryForVuid() != null
                && castOther.getMasterEntryForVuid() != null && this.getMasterEntryForVuid().equals(
                    castOther.getMasterEntryForVuid())))
            && ((this.getInactivationDate() == castOther.getInactivationDate()) || (this.getInactivationDate() != null
                && castOther.getInactivationDate() != null && this.getInactivationDate().equals(
                    castOther.getInactivationDate())))
            && ((this.getRequestStatus() == castOther.getRequestStatus()) || (this.getRequestStatus() != null
                && castOther.getRequestStatus() != null && this.getRequestStatus().equals(castOther.getRequestStatus())))
            && ((this.getItemStatus() == castOther.getItemStatus()) || (this.getItemStatus() != null
                && castOther.getItemStatus() != null && this.getItemStatus().equals(castOther.getItemStatus())))
            && ((this.getRejectReasonText() == castOther.getRejectReasonText()) || (this.getRejectReasonText() != null
                && castOther.getRejectReasonText() != null && this.getRejectReasonText().equals(
                    castOther.getRejectReasonText())))
            && ((this.getRequestRejectReason() == castOther.getRequestRejectReason()) || (this.getRequestRejectReason() != null
                && castOther.getRequestRejectReason() != null && this.getRequestRejectReason().equals(
                    castOther.getRequestRejectReason())))
            && ((this.getRevisionNumber() == castOther.getRevisionNumber()) || (this.getRevisionNumber() != null
                && castOther.getRevisionNumber() != null && this.getRevisionNumber().equals(castOther.getRevisionNumber())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getEplId() == null ? 0 : this.getEplId().hashCode());
        result = 37 * result + (getVuid() == null ? 0 : this.getVuid().hashCode());
        result = 37 * result + (getMasterEntryForVuid() == null ? 0 : this.getMasterEntryForVuid().hashCode());
        result = 37 * result + (getStandardMedRouteName() == null ? 0 : this.getStandardMedRouteName().hashCode());
        result = 37 * result + (getFirstDatabankMedRoute() == null ? 0 : this.getFirstDatabankMedRoute().hashCode());
        result = 37 * result + (getInactivationDate() == null ? 0 : this.getInactivationDate().hashCode());
        result = 37 * result + (getRequestStatus() == null ? 0 : this.getRequestStatus().hashCode());
        result = 37 * result + (getItemStatus() == null ? 0 : this.getItemStatus().hashCode());
        result = 37 * result + (getRejectReasonText() == null ? 0 : this.getRejectReasonText().hashCode());
        result = 37 * result + (getRequestRejectReason() == null ? 0 : this.getRequestRejectReason().hashCode());
        result = 37 * result + (getRevisionNumber() == null ? 0 : this.getRevisionNumber().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());

        return result;
    }

    /**
     * 
     * @return eplStandardMedRoute property
     */
    public EplStandardMedRouteDo getEplStandardMedRoute() {
        return eplStandardMedRoute;
    }

    /**
     * 
     * @param eplStandardMedRoute eplStandardMedRoute property
     */
    public void setEplStandardMedRoute(EplStandardMedRouteDo eplStandardMedRoute) {
        this.eplStandardMedRoute = eplStandardMedRoute;
    }

}
