/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Jul 1, 2008 1:58:45 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


/**
 * 
 * EplSiteUpdateScheduleDo generated by hbm2java
 * @hibernate.class
 */
public class EplSiteUpdateScheduleDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String IN_PROGRESS = "inProgress";
    public static final String SITE_NUMBER = "siteNumber";
    public static final String SOFTWARE_UPDATE_TYPE = "softwareUpdateType";
    public static final String SOFTWARE_UPDATE_VERSION = "softwareUpdateVersion";
    public static final String SCHEDULE_START_DTM = "scheduledStartDtm";
    
    private static final long serialVersionUID = 1L;
    
    private Long id;
    private String siteNumber;
    private String softwareUpdateType;
    private String softwareUpdateVersion;
    private Date startDtm;
    private Date endDtm;
    private String inProgress;
    private Date scheduledStartDtm;
    private String scheduledInterval;
    private String md5sum;

    // Constructors
    
    /**
     * 
     * Default constructor
     * 
     */
    public EplSiteUpdateScheduleDo() {
    }

    /**
     * 
     * minimal constructor
     * 
     * @param id Long
     * @param siteNumber String
     * @param softwareUpdateType String
     * @param softwareUpdateVersion String
     * @param createdBy String
     * @param createdDtm Date
     */
    public EplSiteUpdateScheduleDo(Long id, String siteNumber, String softwareUpdateType, String softwareUpdateVersion, 
                                   String createdBy, Date createdDtm) {
        this.id = id;
        this.siteNumber = siteNumber;
        this.softwareUpdateType = softwareUpdateType;
        this.softwareUpdateVersion = softwareUpdateVersion;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /**
     * 
     * Full constructor
     * 
     * @param id Long
     * @param siteNumber String
     * @param softwareUpdateType String
     * @param softwareUpdateVersion String
     * @param startDtm Date
     * @param endDtm Date
     * @param inProgress String
     * @param scheduledStartDtm Date
     * @param scheduledInterval String
     * @param md5sum String
     * @param createdBy String
     * @param createdDtm Date
     * @param lastModifiedBy String
     * @param lastModifiedDtm Date
     */
    public EplSiteUpdateScheduleDo(Long id, String siteNumber, String softwareUpdateType, String softwareUpdateVersion,
                                   Date startDtm, Date endDtm, String inProgress, Date scheduledStartDtm, 
                                   String scheduledInterval, String md5sum, String createdBy,
                                   Date createdDtm, String lastModifiedBy, Date lastModifiedDtm) {
        this.id = id;
        this.siteNumber = siteNumber;
        this.softwareUpdateType = softwareUpdateType;
        this.softwareUpdateVersion = softwareUpdateVersion;
        this.startDtm = startDtm;
        this.endDtm = endDtm;
        this.inProgress = inProgress;
        this.scheduledStartDtm = scheduledStartDtm;
        this.scheduledInterval = scheduledInterval;
        this.md5sum = md5sum;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
    }

    /**
     * 
     * @return Long
     */
    public Long getId() {
        return this.id;
    }
    
    /**
     * 
     * @param id Long
     */
    public void setId(Long id) {
        this.id = id;
    }
    
    /**
     * 
     * @return String
     */
    public String getSiteNumber() {
        return this.siteNumber;
    }
    
    /**
     * 
     * @param siteNumber String
     */
    public void setSiteNumber(String siteNumber) {
        this.siteNumber = siteNumber;
    }
    
    /**
     * 
     * @return String
     */
    public String getSoftwareUpdateType() {
        return this.softwareUpdateType;
    }
    
    /**
     * 
     * @param softwareUpdateType String
     */
    public void setSoftwareUpdateType(String softwareUpdateType) {
        this.softwareUpdateType = softwareUpdateType;
    }
    
    /**
     * 
     * @return String
     */
    public String getSoftwareUpdateVersion() {
        return this.softwareUpdateVersion;
    }
    
    /**
     * 
     * @param softwareUpdateVersion String
     */
    public void setSoftwareUpdateVersion(String softwareUpdateVersion) {
        this.softwareUpdateVersion = softwareUpdateVersion;
    }
    
    /**
     * 
     * @return Date
     */
    public Date getStartDtm() {
        return this.startDtm;
    }

    /**
     * 
     * @param startDtm Date
     */
    public void setStartDtm(Date startDtm) {
        this.startDtm = startDtm;
    }

    /**
     * 
     * @return Date
     */
    public Date getEndDtm() {
        return this.endDtm;
    }

    /**
     * 
     * @param endDtm Date
     */
    public void setEndDtm(Date endDtm) {
        this.endDtm = endDtm;
    }

    /**
     * 
     * @return String
     */
    public String getInProgress() {
        return this.inProgress;
    }

    /**
     * 
     * @param inProgress String
     */
    public void setInProgress(String inProgress) {
        this.inProgress = inProgress;
    }

    /**
     * 
     * @return Date
     */
    public Date getScheduledStartDtm() {
        return this.scheduledStartDtm;
    }

    /**
     * 
     * @param scheduledStartDtm Date
     */
    public void setScheduledStartDtm(Date scheduledStartDtm) {
        this.scheduledStartDtm = scheduledStartDtm;
    }

    /**
     * 
     * @return String
     */
    public String getScheduledInterval() {
        return this.scheduledInterval;
    }

    /**
     * 
     * @param scheduledInterval String
     */
    public void setScheduledInterval(String scheduledInterval) {
        this.scheduledInterval = scheduledInterval;
    }

    /**
     * 
     * @return String
     */
    public String getMd5sum() {
        return this.md5sum;
    }

    /**
     * 
     * @param md5sum String
     */
    public void setMd5sum(String md5sum) {
        this.md5sum = md5sum;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {

        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("startDtm").append("='").append(getStartDtm()).append("' ");
        buffer.append("endDtm").append("='").append(getEndDtm()).append("' ");
        buffer.append("inProgress").append("='").append(getInProgress()).append("' ");
        buffer.append("scheduledStartDtm").append("='").append(getScheduledStartDtm()).append("' ");
        buffer.append("scheduledInterval").append("='").append(getScheduledInterval()).append("' ");
        buffer.append("md5sum").append("='").append(getMd5sum()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * 
     * @param other Object
     * @return boolean
     * 
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#equals(java.lang.Object)
     */
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplSiteUpdateScheduleDo)) {
            return false;
        }
        
        EplSiteUpdateScheduleDo castOther = (EplSiteUpdateScheduleDo) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && 
                 this.getId().equals(castOther.getId())))
            && ((this.getSiteNumber() == castOther.getSiteNumber()) || (this.getSiteNumber() != null && 
                 castOther.getSiteNumber() != null && this.getSiteNumber().equals(castOther.getSiteNumber())))
            && ((this.getSoftwareUpdateType() == castOther.getSoftwareUpdateType()) || 
                (this.getSoftwareUpdateType() != null && castOther.getSoftwareUpdateType() != null && 
                 this.getSoftwareUpdateType().equals(castOther.getSoftwareUpdateType())))
            && ((this.getSoftwareUpdateVersion() == castOther.getSoftwareUpdateVersion()) || 
                (this.getSoftwareUpdateVersion() != null && castOther.getSoftwareUpdateVersion() != null && 
                 this.getSoftwareUpdateVersion().equals(castOther.getSoftwareUpdateVersion())))
            && ((this.getStartDtm() == castOther.getStartDtm()) || (this.getStartDtm() != null
                && castOther.getStartDtm() != null && this.getStartDtm().equals(castOther.getStartDtm())))
            && ((this.getEndDtm() == castOther.getEndDtm()) || (this.getEndDtm() != null && castOther.getEndDtm() != null && 
                 this.getEndDtm().equals(castOther.getEndDtm())))
            && ((this.getInProgress() == castOther.getInProgress()) || (this.getInProgress() != null
                && castOther.getInProgress() != null && this.getInProgress().equals(castOther.getInProgress())))
            && ((this.getScheduledStartDtm() == castOther.getScheduledStartDtm()) || (this.getScheduledStartDtm() != null
                && castOther.getScheduledStartDtm() != null && this.getScheduledStartDtm().equals(
                    castOther.getScheduledStartDtm())))
            && ((this.getScheduledInterval() == castOther.getScheduledInterval()) || (this.getScheduledInterval() != null
                && castOther.getScheduledInterval() != null && this.getScheduledInterval().equals(
                    castOther.getScheduledInterval())))
            && ((this.getMd5sum() == castOther.getMd5sum()) || (this.getMd5sum() != null && castOther.getMd5sum() != null && 
                 this.getMd5sum().equals(castOther.getMd5sum())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())));
    }

    /**
     * 
     * @return integer
     * 
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#hashCode()
     */
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getSiteNumber() == null ? 0 : this.getSiteNumber().hashCode());
        result = 37 * result + (getSoftwareUpdateType() == null ? 0 : this.getSoftwareUpdateType().hashCode());
        result = 37 * result + (getSoftwareUpdateVersion() == null ? 0 : this.getSoftwareUpdateVersion().hashCode());
        result = 37 * result + (getStartDtm() == null ? 0 : this.getStartDtm().hashCode());
        result = 37 * result + (getEndDtm() == null ? 0 : this.getEndDtm().hashCode());
        result = 37 * result + (getInProgress() == null ? 0 : this.getInProgress().hashCode());
        result = 37 * result + (getScheduledStartDtm() == null ? 0 : this.getScheduledStartDtm().hashCode());
        result = 37 * result + (getScheduledInterval() == null ? 0 : this.getScheduledInterval().hashCode());
        result = 37 * result + (getMd5sum() == null ? 0 : this.getMd5sum().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());
       
        return result;
    }

}
