/**
 * Source file created in 2008 by Southwest Research Institute
 */



package gov.va.med.pharmacy.peps.domain.common.model;


import java.util.Date;


// Generated Oct 15, 2008 11:54:39 AM by Hibernate Tools 3.2.0.betimport java.util.Date;

/**
 * EplSearchCriteriaDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplSearchCriteriaDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    
    public static final String EPL_SEARCH_TEMPLATE_ID = "eplSearchTemplate.eplId";
    
    private static final long serialVersionUID = 1L;

    private EplSearchCriteriaDoKey key;
    private String searchFieldValue;
    private EplSearchTemplateDo eplSearchTemplate;

    // Constructors

    /** default constructor */
    
    public EplSearchCriteriaDo() {
    }

    /** minimal constructor */
    
    public EplSearchCriteriaDo(EplSearchCriteriaDoKey key, String searchFieldValue, String createdBy, Date createdDtm) {
        this.key = key;
        this.searchFieldValue = searchFieldValue;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */
    
    public EplSearchCriteriaDo(EplSearchCriteriaDoKey key, String searchFieldValue, String createdBy, Date createdDtm,
                               String lastModifiedBy, Date lastModifiedDtm, EplSearchTemplateDo eplSearchTemplate) {
        this.key = key;
        this.searchFieldValue = searchFieldValue;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplSearchTemplate = eplSearchTemplate;
    }

    // Property accessors
    public EplSearchCriteriaDoKey getKey() {
        return this.key;
    }

    public void setKey(EplSearchCriteriaDoKey key) {
        this.key = key;
    }

    public String getSearchFieldValue() {
        return this.searchFieldValue;
    }

    public void setSearchFieldValue(String searchFieldValue) {
        this.searchFieldValue = searchFieldValue;
    }
    
    public EplSearchTemplateDo getEplSearchTemplate() {
        return this.eplSearchTemplate;
    }

    public void setEplSearchTemplate(EplSearchTemplateDo eplSearchTemplate) {
        this.eplSearchTemplate = eplSearchTemplate;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("searchFieldValue").append("='").append(getSearchFieldValue()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplSearchCriteriaDo)) {
            return false;
        }
        
        EplSearchCriteriaDo castOther = (EplSearchCriteriaDo) other;

        return ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this
            .getKey().equals(castOther.getKey())))
            && ((this.getSearchFieldValue() == castOther.getSearchFieldValue()) || (this.getSearchFieldValue() != null
                && castOther.getSearchFieldValue() != null && this.getSearchFieldValue().equals(
                    castOther.getSearchFieldValue())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
        result = 37 * result + (getSearchFieldValue() == null ? 0 : this.getSearchFieldValue().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());

        return result;
    }

}
