/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Mar 24, 2008 1:15:53 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


/**
 * EplSynonymDo generated by hbm2java
 * @hibernate.class
 */
public class EplSynonymDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements java.io.Serializable {

    // Fields

    public static final String SYNONYM_NAME = "synonymName";
    public static final String EPL_PRODUCT = "eplProduct";
    public static final String INTENDED_USE = "eplIntendedUs";
    public static final String DISPENSE_UNITS_PER_ORDER_UNIT = "dispenseUnitsPerOrderUnit";
    public static final String EPL_ORDER_UNIT = "eplOrderUnit";
    public static final String PRICE_PER_DISPENSE_UNIT = "pricePerDispenseUnit";
    public static final String PRICE_PER_ORDER_UNIT = "pricePerOrderUnit";
    public static final String VSN = "vsn";
    public static final String NDC_CODE = "ndcCode";
    public static final String VENDOR = "vendor";
    
    private static final long serialVersionUID = 1L;
    
    private Long id;
    private String synonymName;
    private String ndcCode;
    private String vsn;
    private Double dispenseUnitsPerOrderUnit;
    private Double pricePerDispenseUnit;
    private String vendor;
    private Double pricePerOrderUnit;
    private EplIntendedUseDo eplIntendedUs;
    private EplOrderUnitDo eplOrderUnit;
    private EplProductDo eplProduct;

    // Constructors

    /** default constructor */
    
    public EplSynonymDo() {
    }

    
    /** minimal constructor */
    
    public EplSynonymDo(Long id, String synonymName, String ndcCode, String createdBy, Date createdDtm) {
        this.id = id;
        this.synonymName = synonymName;
        this.ndcCode = ndcCode;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */
    
    public EplSynonymDo(Long id, String synonymName, String ndcCode, String vsn, Double dispenseUnitsPerOrderUnit,
                        Double pricePerDispenseUnit, String vendor, Double pricePerOrderUnit, String createdBy,
                        Date createdDtm, String lastModifiedBy, Date lastModifiedDtm, EplIntendedUseDo eplIntendedUs,
                        EplOrderUnitDo eplOrderUnit, EplProductDo eplProduct) {
        this.id = id;
        this.synonymName = synonymName;
        this.ndcCode = ndcCode;
        this.vsn = vsn;
        this.dispenseUnitsPerOrderUnit = dispenseUnitsPerOrderUnit;
        this.pricePerDispenseUnit = pricePerDispenseUnit;
        this.vendor = vendor;
        this.pricePerOrderUnit = pricePerOrderUnit;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplIntendedUs = eplIntendedUs;
        this.eplOrderUnit = eplOrderUnit;
        this.eplProduct = eplProduct;
    }

    // Property accessors
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSynonymName() {
        return this.synonymName;
    }

    public void setSynonymName(String synonymName) {
        this.synonymName = synonymName;
    }

    public String getNdcCode() {
        return this.ndcCode;
    }

    public void setNdcCode(String ndcCode) {
        this.ndcCode = ndcCode;
    }

    public String getVsn() {
        return this.vsn;
    }

    public void setVsn(String vsn) {
        this.vsn = vsn;
    }

    public Double getDispenseUnitsPerOrderUnit() {
        return this.dispenseUnitsPerOrderUnit;
    }

    public void setDispenseUnitsPerOrderUnit(Double dispenseUnitsPerOrderUnit) {
        this.dispenseUnitsPerOrderUnit = dispenseUnitsPerOrderUnit;
    }

    public Double getPricePerDispenseUnit() {
        return this.pricePerDispenseUnit;
    }

    public void setPricePerDispenseUnit(Double pricePerDispenseUnit) {
        this.pricePerDispenseUnit = pricePerDispenseUnit;
    }

    public String getVendor() {
        return this.vendor;
    }

    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    public Double getPricePerOrderUnit() {
        return this.pricePerOrderUnit;
    }

    public void setPricePerOrderUnit(Double pricePerOrderUnit) {
        this.pricePerOrderUnit = pricePerOrderUnit;
    }

    public EplIntendedUseDo getEplIntendedUs() {
        return this.eplIntendedUs;
    }

    public void setEplIntendedUs(EplIntendedUseDo eplIntendedUs) {
        this.eplIntendedUs = eplIntendedUs;
    }

    public EplOrderUnitDo getEplOrderUnit() {
        return this.eplOrderUnit;
    }

    public void setEplOrderUnit(EplOrderUnitDo eplOrderUnit) {
        this.eplOrderUnit = eplOrderUnit;
    }

    public EplProductDo getEplProduct() {
        return this.eplProduct;
    }

    public void setEplProduct(EplProductDo eplProduct) {
        this.eplProduct = eplProduct;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("synonymName").append("='").append(getSynonymName()).append("' ");
        buffer.append("ndcCode").append("='").append(getNdcCode()).append("' ");
        buffer.append("vsn").append("='").append(getVsn()).append("' ");
        buffer.append("dispenseUnitsPerOrderUnit").append("='").append(getDispenseUnitsPerOrderUnit()).append("' ");
        buffer.append("pricePerDispenseUnit").append("='").append(getPricePerDispenseUnit()).append("' ");
        buffer.append("vendor").append("='").append(getVendor()).append("' ");
        buffer.append("pricePerOrderUnit").append("='").append(getPricePerOrderUnit()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplSynonymDo)) {
            return false;
        }
        
        EplSynonymDo castOther = (EplSynonymDo) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId()
            .equals(castOther.getId())))
            && ((this.getSynonymName() == castOther.getSynonymName()) || (this.getSynonymName() != null
                && castOther.getSynonymName() != null && this.getSynonymName().equals(castOther.getSynonymName())))
            && ((this.getNdcCode() == castOther.getNdcCode()) || (this.getNdcCode() != null
                && castOther.getNdcCode() != null && this.getNdcCode().equals(castOther.getNdcCode())))
            && ((this.getVsn() == castOther.getVsn()) || (this.getVsn() != null && castOther.getVsn() != null && this
                .getVsn().equals(castOther.getVsn())))
            && ((this.getDispenseUnitsPerOrderUnit() == castOther.getDispenseUnitsPerOrderUnit()) || (this
                .getDispenseUnitsPerOrderUnit() != null
                && castOther.getDispenseUnitsPerOrderUnit() != null && this.getDispenseUnitsPerOrderUnit().equals(
                    castOther.getDispenseUnitsPerOrderUnit())))
            && ((this.getPricePerDispenseUnit() == castOther.getPricePerDispenseUnit()) || (this.getPricePerDispenseUnit() != null
                && castOther.getPricePerDispenseUnit() != null && this.getPricePerDispenseUnit().equals(
                    castOther.getPricePerDispenseUnit())))
            && ((this.getVendor() == castOther.getVendor()) || (this.getVendor() != null && castOther.getVendor() != null && this
                .getVendor().equals(castOther.getVendor())))
            && ((this.getPricePerOrderUnit() == castOther.getPricePerOrderUnit()) || (this.getPricePerOrderUnit() != null
                && castOther.getPricePerOrderUnit() != null && this.getPricePerOrderUnit().equals(
                    castOther.getPricePerOrderUnit())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())))
            && ((this.getEplIntendedUs() == castOther.getEplIntendedUs()) || (this.getEplIntendedUs() != null
                && castOther.getEplIntendedUs() != null && this.getEplIntendedUs().equals(castOther.getEplIntendedUs())))
            && ((this.getEplOrderUnit() == castOther.getEplOrderUnit()) || (this.getEplOrderUnit() != null
                && castOther.getEplOrderUnit() != null && this.getEplOrderUnit().equals(castOther.getEplOrderUnit())))
            && ((this.getEplProduct() == castOther.getEplProduct()) || (this.getEplProduct() != null
                && castOther.getEplProduct() != null && this.getEplProduct().equals(castOther.getEplProduct())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getSynonymName() == null ? 0 : this.getSynonymName().hashCode());
        result = 37 * result + (getNdcCode() == null ? 0 : this.getNdcCode().hashCode());
        result = 37 * result + (getVsn() == null ? 0 : this.getVsn().hashCode());
        result = 37 * result + (getDispenseUnitsPerOrderUnit() == null ? 0 : this.getDispenseUnitsPerOrderUnit().hashCode());
        result = 37 * result + (getPricePerDispenseUnit() == null ? 0 : this.getPricePerDispenseUnit().hashCode());
        result = 37 * result + (getVendor() == null ? 0 : this.getVendor().hashCode());
        result = 37 * result + (getPricePerOrderUnit() == null ? 0 : this.getPricePerOrderUnit().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());
        result = 37 * result + (getEplIntendedUs() == null ? 0 : this.getEplIntendedUs().hashCode());
        result = 37 * result + (getEplOrderUnit() == null ? 0 : this.getEplOrderUnit().hashCode());
        result = 37 * result + (getEplProduct() == null ? 0 : this.getEplProduct().hashCode());
       
        return result;
    }

}
