/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Jul 10, 2008 10:26:36 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


/**
 * EplSessionPreferenceDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplSessionPreferenceDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String EPL_USER = "eplUser";
    
    private static final long serialVersionUID = 1L;

    private EplSessionPreferenceDoKey key;
    private String prefValue;
    private EplUserDo eplUser;

    // Constructors

    /** default constructor */
    
    public EplSessionPreferenceDo() {
        this(new EplSessionPreferenceDoKey(), null, null, null); //ensure doKey is never null
    }

    /** minimal constructor */
    
    public EplSessionPreferenceDo(EplSessionPreferenceDoKey key, String prefValue, String createdBy, Date createdDtm) {
        this.key = key;
        this.prefValue = prefValue;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */
    
    public EplSessionPreferenceDo(EplSessionPreferenceDoKey key, String prefValue, String createdBy, Date createdDtm,
                                  String lastModifiedBy, Date lastModifiedDtm, EplUserDo eplUser) {
        this.key = key;
        this.prefValue = prefValue;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplUser = eplUser;
    }

    // Property accessors
    public EplSessionPreferenceDoKey getKey() {
        return this.key;
    }

    public void setKey(EplSessionPreferenceDoKey key) {
        this.key = key;
    }

    public String getPrefValue() {
        return this.prefValue;
    }

    public void setPrefValue(String prefValue) {
        this.prefValue = prefValue;
    }

    public EplUserDo getEplUser() {
        return this.eplUser;
    }

    public void setEplUser(EplUserDo eplUser) {
        this.eplUser = eplUser;
        this.key.setUserIdFk(eplUser.getId());
    }
    
    public void setPrefName(String prefName) {
        this.key.setPrefName(prefName);
    }
    
    public String getPrefName() {
        return this.key.getPrefName();
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("prefValue").append("='").append(getPrefValue()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplSessionPreferenceDo)) {
            return false;
        }

        EplSessionPreferenceDo castOther = (EplSessionPreferenceDo) other;

        return ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this
            .getKey().equals(castOther.getKey())))
            && ((this.getPrefValue() == castOther.getPrefValue()) || (this.getPrefValue() != null
                && castOther.getPrefValue() != null && this.getPrefValue().equals(castOther.getPrefValue())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
        result = 37 * result + (getPrefValue() == null ? 0 : this.getPrefValue().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());

        return result;
    }

}
