/* Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Mar 13, 2008 4:11:36 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


/**
 * EplSeqNumDo generated by hbm2java
 * @hibernate.class
 */
public class EplSiteConfigDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements java.io.Serializable {

    // Fields

    private static final long serialVersionUID = 1L;
    
    private Integer siteNumber;
    private String siteName;
    private String serverName;
    private String eplVersion;
    private Date eplVersionDtm;

    // Constructors

    /** default constructor */
    
    public EplSiteConfigDo() {
    }

    /** minimal constructor */
    
    public EplSiteConfigDo(Integer siteNumber, String siteName, String serverName, String eplVersion, Date eplVersionDtm,
                           String createdBy, Date createdDtm) {
        this.siteNumber = siteNumber;
        this.siteName = siteName;
        this.serverName = serverName;
        this.eplVersion = eplVersion;
        this.eplVersionDtm = eplVersionDtm;
    }

    /** full constructor */
    
    public EplSiteConfigDo(Integer siteNumber, String siteName, String serverName, String eplVersion, Date eplVersionDtm,
                           String createdBy, Date createdDtm, String lastModifiedBy, Date lastModifiedDtm) {
        this.siteNumber = siteNumber;
        this.siteName = siteName;
        this.serverName = serverName;
        this.eplVersion = eplVersion;
        this.eplVersionDtm = eplVersionDtm;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
    }

    // Property accessors
    public Integer getSiteNumber() {
        return this.siteNumber;
    }

    public void setSiteNumber(Integer siteNumber) {
        this.siteNumber = siteNumber;
    }

    public String getSiteName() {
        return this.siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    public String getServerName() {
        return this.serverName;
    }

    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    public String getEplVersion() {
        return this.eplVersion;
    }

    public void setEplVersion(String eplVersion) {
        this.eplVersion = eplVersion;
    }

    public Date getEplVersionDtm() {
        return this.eplVersionDtm;
    }

    public void setEplVersionDtm(Date eplVersionDtm) {
        this.eplVersionDtm = eplVersionDtm;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("siteName").append("='").append(getSiteName()).append("' ");
        buffer.append("serverName").append("='").append(getServerName()).append("' ");
        buffer.append("eplVersion").append("='").append(getEplVersion()).append("' ");
        buffer.append("eplVersionDtm").append("='").append(getEplVersionDtm()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplSiteConfigDo)) {
            return false;
        }
        
        EplSiteConfigDo castOther = (EplSiteConfigDo) other;

        return ((this.getSiteNumber() == castOther.getSiteNumber()) || (this.getSiteNumber() != null
            && castOther.getSiteNumber() != null && this.getSiteNumber().equals(castOther.getSiteNumber())))
            && ((this.getSiteName() == castOther.getSiteName()) || (this.getSiteName() != null
                && castOther.getSiteName() != null && this.getSiteName().equals(castOther.getSiteName())))
            && ((this.getServerName() == castOther.getServerName()) || (this.getServerName() != null
                && castOther.getServerName() != null && this.getServerName().equals(castOther.getServerName())))
            && ((this.getEplVersion() == castOther.getEplVersion()) || (this.getEplVersion() != null
                && castOther.getEplVersion() != null && this.getEplVersion().equals(castOther.getEplVersion())))
            && ((this.getEplVersionDtm() == castOther.getEplVersionDtm()) || (this.getEplVersionDtm() != null
                && castOther.getEplVersionDtm() != null && this.getEplVersionDtm().equals(castOther.getEplVersionDtm())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getSiteNumber() == null ? 0 : this.getSiteNumber().hashCode());
        result = 37 * result + (getSiteName() == null ? 0 : this.getSiteName().hashCode());
        result = 37 * result + (getServerName() == null ? 0 : this.getServerName().hashCode());
        result = 37 * result + (getEplVersion() == null ? 0 : this.getEplVersion().hashCode());
        result = 37 * result + (getEplVersionDtm() == null ? 0 : this.getEplVersionDtm().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());
        
        return result;
    }

}
