/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Mar 2, 2008 2:06:48 PM by Hibernate Tools 3.2.0.beta8

/**
 * EplVadfAssocValueDoKey generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplVadfAssocValueDoKey implements java.io.Serializable {

    // Fields    
    public static final String LIST_VALUE = "listValue";
    
    private static final long serialVersionUID = 1L;

    private Long vadfOwnerIdFk;
    private String listValue;
    private Long vadfIdFk;

    // Constructors
    
    /**
     * default constructor
     */
    public EplVadfAssocValueDoKey() {
    }
    
    /**
     *full constructor 
     * 
     * @param vadfOwnerIdFk of type Long
     * @param listValue of type String
     * @param vadfIdFk of type Long
     */
    public EplVadfAssocValueDoKey(Long vadfOwnerIdFk, String listValue, Long vadfIdFk) {
        this.vadfOwnerIdFk = vadfOwnerIdFk;
        this.listValue = listValue;
        this.vadfIdFk = vadfIdFk;
    }

    // Property accessors
    
    /**
     * @return Long
     */
    public Long getVadfOwnerIdFk() {
        return this.vadfOwnerIdFk;
    }

    /**
     * 
     * 
     * @param vadfOwnerIdFk property
     */
    public void setVadfOwnerIdFk(Long vadfOwnerIdFk) {
        this.vadfOwnerIdFk = vadfOwnerIdFk;
    }

    /**
     * 
     * 
     * @return String
     */
    public String getListValue() {
        return this.listValue;
    }

    /**
     * 
     * 
     * @param listValue property
     */
    public void setListValue(String listValue) {
        this.listValue = listValue;
    }

    /**
     * 
     * 
     * @return Long
     */
    public Long getVadfIdFk() {
        return this.vadfIdFk;
    }

    /**
     * 
     * 
     * @param vadfIdFk property
     */
    public void setVadfIdFk(Long vadfIdFk) {
        this.vadfIdFk = vadfIdFk;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("listValue").append("='").append(getListValue()).append("' ");
        buffer.append("vadfIdFk").append("='").append(getVadfIdFk()).append("' ");
        buffer.append("vadfOwnerIdFk").append("='").append(getVadfOwnerIdFk()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }
    
    /**
     * 
     * 
     * @param other the object
     * @return boolean
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplVadfAssocValueDoKey)) {
            return false;
        }

        EplVadfAssocValueDoKey castOther = (EplVadfAssocValueDoKey) other;

        return ((this.getVadfOwnerIdFk() == castOther.getVadfOwnerIdFk()) || (this.getVadfOwnerIdFk() != null
            && castOther.getVadfOwnerIdFk() != null && this.getVadfOwnerIdFk().equals(castOther.getVadfOwnerIdFk())))
            && ((this.getListValue() == castOther.getListValue()) || (this.getListValue() != null
                && castOther.getListValue() != null && this.getListValue().equals(castOther.getListValue())))
            && ((this.getVadfIdFk() == castOther.getVadfIdFk()) || (this.getVadfIdFk() != null
                && castOther.getVadfIdFk() != null && this.getVadfIdFk().equals(castOther.getVadfIdFk())));
    }

    /**
     * 
     * 
     * @return int
     * 
     * @see java.lang.Object#hashCode()
     */
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getVadfOwnerIdFk() == null ? 0 : this.getVadfOwnerIdFk().hashCode());
        result = 37 * result + (getListValue() == null ? 0 : this.getListValue().hashCode());
        result = 37 * result + (getVadfIdFk() == null ? 0 : this.getVadfIdFk().hashCode());

        return result;
    }

}
