/**
 * Source file created in 2006 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


// Generated Mar 2, 2008 2:06:48 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;


/**
 * EplVadfAssocValueDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplVadfAssocValueDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
    java.io.Serializable {

    // Fields
    public static final String EPL_VA_DF_OWNER = "eplVadfOwner";
    public static final String EPL_VA_DF_OWNER_ID = "eplVadfOwner.id";
    public static final String EPL_VA_DF_LOV = "eplVadfLov";
    public static final String KEY = "key";

    private static final long serialVersionUID = 1L;
    
    private EplVadfAssocValueDoKey key;
    private EplVadfLovDo eplVadfLov;
    private EplVadfOwnerDo eplVadfOwner;
    private EplVaDfDo eplVaDf;

    // Constructors

    /**
     * default constructor
     */
    public EplVadfAssocValueDo() {
    }

    /**
     * minimal constructor
     * 
     * @param key of type EplVadfAssocValueDoKey
     * @param createdBy of type String
     * @param createdDtm of type Date
     */
    public EplVadfAssocValueDo(EplVadfAssocValueDoKey key, String createdBy, Date createdDtm) {
        this.key = key;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /**
     * full constructor
     * 
     * @param key of type EplVadfAssocValueDoKey
     * @param createdBy of type String
     * @param createdDtm of type Date
     * @param lastModifiedBy of type String
     * @param lastModifiedDtm of type Date
     * @param eplVadfLov of type EplVadfLovDo
     * @param eplVadfOwner of type EplVadfOwnerDo
     */
    public EplVadfAssocValueDo(EplVadfAssocValueDoKey key, String createdBy, Date createdDtm, String lastModifiedBy,
                               Date lastModifiedDtm, EplVadfLovDo eplVadfLov, EplVadfOwnerDo eplVadfOwner) {
        this.key = key;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplVadfLov = eplVadfLov;
        this.eplVadfOwner = eplVadfOwner;
    }

    // Property accessors

    /**
     * @return EplVadfAssocValueDoKey
     */
    public EplVadfAssocValueDoKey getKey() {
        return this.key;
    }

    /**
     * 
     * 
     * @param key property
     */
    public void setKey(EplVadfAssocValueDoKey key) {
        this.key = key;
    }

    /**
     * 
     * 
     * @return EplVadfLovDo
     */
    public EplVadfLovDo getEplVadfLov() {
        return this.eplVadfLov;
    }

    /**
     * 
     * 
     * @param eplVadfLov property
     */
    public void setEplVadfLov(EplVadfLovDo eplVadfLov) {
        this.eplVadfLov = eplVadfLov;
    }

    /**
     * 
     * 
     * @return EplVadfOwnerDo
     */
    public EplVadfOwnerDo getEplVadfOwner() {
        return this.eplVadfOwner;
    }

    /**
     * 
     * 
     * @param eplVadfOwner property
     */
    public void setEplVadfOwner(EplVadfOwnerDo eplVadfOwner) {
        this.eplVadfOwner = eplVadfOwner;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * 
     * 
     * @param other the object
     * @return boolean
     * 
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#equals(java.lang.Object)
     */
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplVadfAssocValueDo)) {
            return false;
        }

        EplVadfAssocValueDo castOther = (EplVadfAssocValueDo) other;

        return ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null && this
            .getKey().equals(castOther.getKey())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())));
    }

    /**
     * 
     * 
     * @return int
     * 
     * @see gov.va.med.pharmacy.peps.domain.common.model.DataObject#hashCode()
     */
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());

        return result;
    }
}
