/** 
 * Source file created in 2006 by Southwest Research Institute
 * 
 * Generated Jun 25, 2008 3:24:38 PM by Hibernate Tools 3.2.0.beta8
 * Generated and Edited Aug 24, 2011 10:37:08 AM by Hibernate Tools 3.2.4.GA
 */


package gov.va.med.pharmacy.peps.domain.common.model;


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;


/**
 * EplVaGenNameDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplVaGenNameDo extends
        gov.va.med.pharmacy.peps.domain.common.model.DataObject implements
        java.io.Serializable {

    // Fields
    public static final String EPL_ID = "eplId";
    public static final String NAME = "genericName";
    public static final String ITEM_STATUS = "itemStatus";
    public static final String REQUEST_STATUS = "requestStatus";
    public static final String INACTIVATION_DATE = "inactivationDate";
    public static final String NDF_GENERIC_IEN = "ndfGenericIen";

    private static final long serialVersionUID = 1L;

    private Long eplId;
    private String vuid;
    private String masterEntryForVuid;
    private String genericName;
    private java.util.Date inactivationDate;
    private String requestStatus;
    private String itemStatus;
    private String rejectReasonText;
    private String requestRejectReason;
    private Long revisionNumber;
    private Long ndfGenericIen;
    private Set<EplProductDo> eplProducts = new HashSet<EplProductDo>(0);

    // Constructors

    /** default constructor */

    public EplVaGenNameDo() {
    }

    /** minimal constructor */

    public EplVaGenNameDo(Long eplId, String vuid, String masterEntryForVuid,
            String genericName, String requestStatus, String itemStatus,
            Long revisionNumber, String createdBy, Timestamp createdDtm) {
        this.eplId = eplId;
        this.vuid = vuid;
        this.masterEntryForVuid = masterEntryForVuid;
        this.genericName = genericName;
        this.requestStatus = requestStatus;
        this.itemStatus = itemStatus;
        this.revisionNumber = revisionNumber;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */

    public EplVaGenNameDo(Long eplId, String vuid, String masterEntryForVuid,
            String genericName, Timestamp inactivationDate,
            String requestStatus, String itemStatus, String rejectReasonText,
            String requestRejectReason, Long revisionNumber, Long ndfGenericIen, String createdBy,
            Timestamp createdDtm, String lastModifiedBy,
            Timestamp lastModifiedDtm, Set<EplProductDo> eplProducts) {
        this.eplId = eplId;
        this.vuid = vuid;
        this.masterEntryForVuid = masterEntryForVuid;
        this.genericName = genericName;
        this.inactivationDate = inactivationDate;
        this.requestStatus = requestStatus;
        this.itemStatus = itemStatus;
        this.rejectReasonText = rejectReasonText;
        this.requestRejectReason = requestRejectReason;
        this.revisionNumber = revisionNumber;
        this.ndfGenericIen = ndfGenericIen;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplProducts = eplProducts;
    }

    // Property accessors
    public Long getEplId() {
        return this.eplId;
    }

    public void setEplId(Long eplId) {
        this.eplId = eplId;
    }
    
   /**
    * getNdfGenericIen
    * @return ndfGenericIen
    */
    public Long getNdfGenericIen() {
        return this.ndfGenericIen;
    }

    /**
     * setNdfGenericIen
     * @param ndfGenericIen ndfGenericIen
     */
    public void setNdfGenericIen(Long ndfGenericIen) {
        this.ndfGenericIen = ndfGenericIen;
    }

    public String getVuid() {
        return this.vuid;
    }

    public void setVuid(String vuid) {
        this.vuid = vuid;
    }

    public String getMasterEntryForVuid() {
        return this.masterEntryForVuid;
    }

    public void setMasterEntryForVuid(String masterEntryForVuid) {
        this.masterEntryForVuid = masterEntryForVuid;
    }

    public String getGenericName() {
        return this.genericName;
    }

    public void setGenericName(String genericName) {
        this.genericName = genericName;
    }

    public java.util.Date getInactivationDate() {
        return this.inactivationDate;
    }

    public void setInactivationDate(java.util.Date inactivationDate) {
        this.inactivationDate = inactivationDate;
    }

    public String getRequestStatus() {
        return this.requestStatus;
    }

    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }

    public String getItemStatus() {
        return this.itemStatus;
    }

    public void setItemStatus(String itemStatus) {
        this.itemStatus = itemStatus;
    }

    public String getRejectReasonText() {
        return this.rejectReasonText;
    }

    public void setRejectReasonText(String rejectReasonText) {
        this.rejectReasonText = rejectReasonText;
    }

    public String getRequestRejectReason() {
        return this.requestRejectReason;
    }

    public void setRequestRejectReason(String requestRejectReason) {
        this.requestRejectReason = requestRejectReason;
    }

    public Long getRevisionNumber() {
        return this.revisionNumber;
    }

    public void setRevisionNumber(Long revisionNumber) {
        this.revisionNumber = revisionNumber;
    }

    public Set<EplProductDo> getEplProducts() {
        return this.eplProducts;
    }

    public void setEplProducts(Set<EplProductDo> eplProducts) {
        this.eplProducts = eplProducts;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@")
                .append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("vuid").append("='").append(getVuid()).append("' ");
        buffer.append("masterEntryForVuid").append("='")
                .append(this.getMasterEntryForVuid()).append("' ");
        buffer.append("genericName").append("='").append(getGenericName())
                .append("' ");
        buffer.append("inactivationDate").append("='")
                .append(getInactivationDate()).append("' ");
        buffer.append("requestStatus").append("='").append(getRequestStatus())
                .append("' ");
        buffer.append("itemStatus").append("='").append(getItemStatus())
                .append("' ");
        buffer.append("rejectReasonText").append("='")
                .append(getRejectReasonText()).append("' ");
        buffer.append("requestRejectReason").append("='")
                .append(getRequestRejectReason()).append("' ");
        buffer.append("revisionNumber").append("='")
                .append(getRevisionNumber()).append("' ");
        buffer.append("ndfGenericIen").append("='")
                .append(getNdfGenericIen()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy())
                .append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm())
                .append("' ");
        buffer.append("lastModifiedBy").append("='")
                .append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='")
                .append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplVaGenNameDo)) {
            return false;
        }

        EplVaGenNameDo castOther = (EplVaGenNameDo) other;

        return ((this.getEplId() == castOther.getEplId()) || (this.getEplId() != null
                && castOther.getEplId() != null && this.getEplId().equals(
                    castOther.getEplId())))
                && ((this.getVuid() == castOther.getVuid()) || (this.getVuid() != null
                        && castOther.getVuid() != null && this.getVuid()
                        .equals(castOther.getVuid())))
                && ((this.getMasterEntryForVuid() == castOther
                        .getMasterEntryForVuid()) || (this
                        .getMasterEntryForVuid() != null
                        && castOther.getMasterEntryForVuid() != null && this
                        .getMasterEntryForVuid().equals(
                                castOther.getMasterEntryForVuid())))
                && ((this.getGenericName() == castOther.getGenericName()) || (this
                        .getGenericName() != null
                        && castOther.getGenericName() != null && this
                        .getGenericName().equals(castOther.getGenericName())))
                && ((this.getInactivationDate() == castOther
                        .getInactivationDate()) || (this.getInactivationDate() != null
                        && castOther.getInactivationDate() != null && this
                        .getInactivationDate().equals(
                                castOther.getInactivationDate())))
                && ((this.getRequestStatus() == castOther.getRequestStatus()) || (this
                        .getRequestStatus() != null
                        && castOther.getRequestStatus() != null && this
                        .getRequestStatus()
                        .equals(castOther.getRequestStatus())))
                && ((this.getItemStatus() == castOther.getItemStatus()) || (this
                        .getItemStatus() != null
                        && castOther.getItemStatus() != null && this
                        .getItemStatus().equals(castOther.getItemStatus())))
                && ((this.getRejectReasonText() == castOther
                        .getRejectReasonText()) || (this.getRejectReasonText() != null
                        && castOther.getRejectReasonText() != null && this
                        .getRejectReasonText().equals(
                                castOther.getRejectReasonText())))
                && ((this.getRequestRejectReason() == castOther
                        .getRequestRejectReason()) || (this
                        .getRequestRejectReason() != null
                        && castOther.getRequestRejectReason() != null && this
                        .getRequestRejectReason().equals(
                                castOther.getRequestRejectReason())))
                && ((this.getRevisionNumber() == castOther.getRevisionNumber()) || (this
                        .getRevisionNumber() != null
                        && castOther.getRevisionNumber() != null && this
                        .getRevisionNumber().equals(
                                castOther.getRevisionNumber())))
                && ((this.getNdfGenericIen() == castOther.getNdfGenericIen()) || (this
                        .getNdfGenericIen() != null
                        && castOther.getNdfGenericIen() != null && this
                        .getNdfGenericIen().equals(
                                castOther.getNdfGenericIen())))
                && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
                        .getCreatedBy() != null
                        && castOther.getCreatedBy() != null && this
                        .getCreatedBy().equals(castOther.getCreatedBy())))
                && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this
                        .getCreatedDtm() != null
                        && castOther.getCreatedDtm() != null && this
                        .getCreatedDtm().equals(castOther.getCreatedDtm())))
                && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this
                        .getLastModifiedBy() != null
                        && castOther.getLastModifiedBy() != null && this
                        .getLastModifiedBy().equals(
                                castOther.getLastModifiedBy())))
                && ((this.getLastModifiedDtm() == castOther
                        .getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                        && castOther.getLastModifiedDtm() != null && this
                        .getLastModifiedDtm().equals(
                                castOther.getLastModifiedDtm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getEplId() == null ? 0 : this.getEplId().hashCode());
        result = 37 * result
                + (getVuid() == null ? 0 : this.getVuid().hashCode());
        result = 37
                * result
                + (getGenericName() == null ? 0 : this.getGenericName()
                        .hashCode());
        result = 37
                * result
                + (getInactivationDate() == null ? 0 : this
                        .getInactivationDate().hashCode());
        result = 37
                * result
                + (getRequestStatus() == null ? 0 : this.getRequestStatus()
                        .hashCode());
        result = 37
                * result
                + (getItemStatus() == null ? 0 : this.getItemStatus()
                        .hashCode());
        result = 37
                * result
                + (getRejectReasonText() == null ? 0 : this
                        .getRejectReasonText().hashCode());
        result = 37
                * result
                + (getRequestRejectReason() == null ? 0 : this
                        .getRequestRejectReason().hashCode());
        result = 37
                * result
                + (getRevisionNumber() == null ? 0 : this.getRevisionNumber()
                        .hashCode());
        result = 37 * result + (getNdfGenericIen() == null ? 0 : this.getNdfGenericIen().hashCode());
        result = 37 * result
                + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37
                * result
                + (getCreatedDtm() == null ? 0 : this.getCreatedDtm()
                        .hashCode());
        result = 37
                * result
                + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy()
                        .hashCode());
        result = 37
                * result
                + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm()
                        .hashCode());

        return result;
    }

}
