/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * EplVadfOwnerDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplVadfOwnerDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements java.io.Serializable {

    // Fields
    public static final String EPL_VA_DF_NON_LIST_VALUES = "eplVadfNonlistValues";
    public static final String EPL_VA_DF_ASSOC_VALUES = "eplVadfAssocValues";
    public static final String EPL_VA_DF_MULTI_TEXTS = "eplMultiTexts";
    public static final String EPL_NDC = "eplNdc";
    public static final String EPL_PRODUCT = "eplProduct";
    public static final String EPL_ORDERABLE_ITEM = "eplOrderableItem";
    public static final String EPL_VADF_OWNER = "eplVadfOwner";
    public static final String ITEM_OWNER_ID = "vadfOwnerId";
    public static final String ITEM_OWNER_TYPE = "vadfOwnerType";
    public static final String EPL_VADF_VALUES_VIEW = "eplVadfValuesView";
    public static final String ID = "id";
    
    private static final long serialVersionUID = 1L;

    private Long id;
    private String vadfOwnerType;
    private Long vadfOwnerId;
    private Set<EplVadfAssocValueDo> eplVadfAssocValues = new HashSet<EplVadfAssocValueDo>(0);
    private Set<EplVadfNonlistValueDo> eplVadfNonlistValues = new HashSet<EplVadfNonlistValueDo>(0);
    private Set<EplVadfEditablePropertyDo> eplVadfEditableProperties = new HashSet<EplVadfEditablePropertyDo>(0);

    private Set<EplMultiTextDo> eplMultiTexts = new HashSet<EplMultiTextDo>(0);
    private EplOrderableItemDo eplOrderableItem;
    private EplProductDo eplProduct;
    private EplNdcDo eplNdc;

    private Set<EplVadfValuesViewDo> eplVadfValuesView = new HashSet<EplVadfValuesViewDo>(0);

    // Constructors

    /** default constructor */

    public EplVadfOwnerDo() {
    }

    /** minimal constructor */

    public EplVadfOwnerDo(Long id, String vadfOwnerType, Long vadfOwnerId, String createdBy, Date createdDtm) {
        this.id = id;
        this.vadfOwnerType = vadfOwnerType;
        this.vadfOwnerId = vadfOwnerId;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */

    public EplVadfOwnerDo(Long id, String vadfOwnerType, Long vadfOwnerId, String createdBy, Date createdDtm,
                          String lastModifiedBy, Date lastModifiedDtm, Set<EplVadfAssocValueDo> eplVadfAssocValues,
                          Set<EplVadfNonlistValueDo> eplVadfNonlistValues,
                          Set<EplVadfEditablePropertyDo> eplVadfEditableProperties, Set<EplMultiTextDo> eplMultiTexts,
                          EplOrderableItemDo eplOrderableItem, EplProductDo eplProduct, EplNdcDo eplNdc) {
        this.id = id;
        this.vadfOwnerType = vadfOwnerType;
        this.vadfOwnerId = vadfOwnerId;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
        this.setLastModifiedBy(lastModifiedBy);
        this.setLastModifiedDtm(lastModifiedDtm);
        this.eplVadfAssocValues = eplVadfAssocValues;
        this.eplVadfNonlistValues = eplVadfNonlistValues;
        this.eplVadfEditableProperties = eplVadfEditableProperties;
        this.eplMultiTexts = eplMultiTexts;
        this.eplOrderableItem = eplOrderableItem;
        this.eplProduct = eplProduct;
        this.eplNdc = eplNdc;
    }

    // Property accessors
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVadfOwnerType() {
        return this.vadfOwnerType;
    }

    public void setVadfOwnerType(String vadfOwnerType) {
        this.vadfOwnerType = vadfOwnerType;
    }

    public Long getVadfOwnerId() {
        return this.vadfOwnerId;
    }

    public void setVadfOwnerId(Long vadfOwnerId) {
        this.vadfOwnerId = vadfOwnerId;
    }

    public Set<EplVadfAssocValueDo> getEplVadfAssocValues() {
        return this.eplVadfAssocValues;
    }

    public void setEplVadfAssocValues(Set<EplVadfAssocValueDo> eplVadfAssocValues) {
        this.eplVadfAssocValues = eplVadfAssocValues;
    }

    public Set<EplVadfNonlistValueDo> getEplVadfNonlistValues() {
        return this.eplVadfNonlistValues;
    }

    public void setEplVadfNonlistValues(Set<EplVadfNonlistValueDo> eplVadfNonlistValues) {
        this.eplVadfNonlistValues = eplVadfNonlistValues;
    }

    public Set<EplVadfEditablePropertyDo> getEplVadfEditableProperties() {
        return this.eplVadfEditableProperties;
    }

    public void setEplVadfEditableProperties(Set<EplVadfEditablePropertyDo> eplVadfEditableProperties) {
        this.eplVadfEditableProperties = eplVadfEditableProperties;
    }

    public Set<EplMultiTextDo> getEplMultiTexts() {
        return this.eplMultiTexts;
    }

    public void setEplMultiTexts(Set<EplMultiTextDo> eplMultiTexts) {
        this.eplMultiTexts = eplMultiTexts;
    }

    public EplOrderableItemDo getEplOrderableItem() {
        return this.eplOrderableItem;
    }

    public void setEplOrderableItem(EplOrderableItemDo eplOrderableItem) {
        this.eplOrderableItem = eplOrderableItem;
    }

    public EplProductDo getEplProduct() {
        return this.eplProduct;
    }

    public void setEplProduct(EplProductDo eplProduct) {
        this.eplProduct = eplProduct;
    }

    public EplNdcDo getEplNdc() {
        return this.eplNdc;
    }

    public void setEplNdc(EplNdcDo eplNdc) {
        this.eplNdc = eplNdc;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("vadfOwnerType").append("='").append(getVadfOwnerType()).append("' ");
        buffer.append("vadfOwnerId").append("='").append(getVadfOwnerId()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof EplVadfOwnerDo)) {
            return false;
        }

        EplVadfOwnerDo castOther = (EplVadfOwnerDo) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId()
            .equals(castOther.getId())))
            && ((this.getVadfOwnerType() == castOther.getVadfOwnerType()) || (this.getVadfOwnerType() != null
                && castOther.getVadfOwnerType() != null && this.getVadfOwnerType().equals(castOther.getVadfOwnerType())))
            && ((this.getVadfOwnerId() == castOther.getVadfOwnerId()) || (this.getVadfOwnerId() != null
                && castOther.getVadfOwnerId() != null && this.getVadfOwnerId().equals(castOther.getVadfOwnerId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getVadfOwnerType() == null ? 0 : this.getVadfOwnerType().hashCode());
        result = 37 * result + (getVadfOwnerId() == null ? 0 : this.getVadfOwnerId().hashCode());

        return result;
    }

    /**
     * 
     * @return eplVadfValues property
     */
    public Set<EplVadfValuesViewDo> getEplVadfValuesView() {
        return eplVadfValuesView;
    }

    /**
     * 
     * @param eplVadfValues eplVadfValues property
     */
    public void setEplVadfValuesView(Set<EplVadfValuesViewDo> eplVadfValues) {
        this.eplVadfValuesView = eplVadfValues;
    }

}
