/**
 * Source file created in 2008 by Southwest Research Institute
 */


package gov.va.med.pharmacy.peps.domain.common.model;


import java.util.Date;


/**
 * EplWardDo generated by hbm2java
 * 
 * @hibernate.class
 */
public class EplWardDo extends gov.va.med.pharmacy.peps.domain.common.model.DataObject implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    // Fields

    private Long id;
    private String ward;
    private String wardAdminTimes;
    private EplAdminScheduleDo eplAdminSchedule;

    // Constructors

    /** default constructor */

    public EplWardDo() {
    }

    /** minimal constructor */

    public EplWardDo(Long id, String ward, String wardAdminTimes, String createdBy, Date createdDtm) {
        this.id = id;
        this.ward = ward;
        this.wardAdminTimes = wardAdminTimes;
        this.setCreatedBy(createdBy);
        this.setCreatedDtm(createdDtm);
    }

    /** full constructor */

    public EplWardDo(Long id, String ward, String wardAdminTimes, String createdBy, Date createdDtm,
                     String lastModifiedBy, Date lastModifiedDtm, EplAdminScheduleDo eplAdminSchedule) {
        this.id = id;
        this.ward = ward;
        this.wardAdminTimes = wardAdminTimes;
        this.eplAdminSchedule = eplAdminSchedule;
    }

    // Property accessors
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWard() {
        return this.ward;
    }

    public void setWard(String ward) {
        this.ward = ward;
    }

    public String getWardAdminTimes() {
        return this.wardAdminTimes;
    }

    public void setWardAdminTimes(String wardAdminTimes) {
        this.wardAdminTimes = wardAdminTimes;
    }

    public EplAdminScheduleDo getEplAdminSchedule() {
        return this.eplAdminSchedule;
    }

    public void setEplAdminSchedule(EplAdminScheduleDo eplAdminSchedule) {
        this.eplAdminSchedule = eplAdminSchedule;
    }

    /**
     * toString
     * 
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("ward").append("='").append(getWard()).append("' ");
        buffer.append("wardAdminTimes").append("='").append(getWardAdminTimes()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("createdDtm").append("='").append(getCreatedDtm()).append("' ");
        buffer.append("lastModifiedBy").append("='").append(getLastModifiedBy()).append("' ");
        buffer.append("lastModifiedDtm").append("='").append(getLastModifiedDtm()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        
        if ((other == null)) {
            return false;
        }
        
        if (!(other instanceof EplWardDo)) {
            return false;
        }
        
        EplWardDo castOther = (EplWardDo) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId()
            .equals(castOther.getId())))
            && ((this.getWard() == castOther.getWard()) || (this.getWard() != null && castOther.getWard() != null && this
                .getWard().equals(castOther.getWard())))
            && ((this.getWardAdminTimes() == castOther.getWardAdminTimes()) || (this.getWardAdminTimes() != null
                && castOther.getWardAdminTimes() != null && this.getWardAdminTimes().equals(castOther.getWardAdminTimes())))
            && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
            && ((this.getCreatedDtm() == castOther.getCreatedDtm()) || (this.getCreatedDtm() != null
                && castOther.getCreatedDtm() != null && this.getCreatedDtm().equals(castOther.getCreatedDtm())))
            && ((this.getLastModifiedBy() == castOther.getLastModifiedBy()) || (this.getLastModifiedBy() != null
                && castOther.getLastModifiedBy() != null && this.getLastModifiedBy().equals(castOther.getLastModifiedBy())))
            && ((this.getLastModifiedDtm() == castOther.getLastModifiedDtm()) || (this.getLastModifiedDtm() != null
                && castOther.getLastModifiedDtm() != null && this.getLastModifiedDtm()
                .equals(castOther.getLastModifiedDtm())))
            && ((this.getEplAdminSchedule() == castOther.getEplAdminSchedule()) || (this.getEplAdminSchedule() != null
                && castOther.getEplAdminSchedule() != null && this.getEplAdminSchedule().equals(
                    castOther.getEplAdminSchedule())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getWard() == null ? 0 : this.getWard().hashCode());
        result = 37 * result + (getWardAdminTimes() == null ? 0 : this.getWardAdminTimes().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getCreatedDtm() == null ? 0 : this.getCreatedDtm().hashCode());
        result = 37 * result + (getLastModifiedBy() == null ? 0 : this.getLastModifiedBy().hashCode());
        result = 37 * result + (getLastModifiedDtm() == null ? 0 : this.getLastModifiedDtm().hashCode());
        result = 37 * result + (getEplAdminSchedule() == null ? 0 : this.getEplAdminSchedule().hashCode());
        
        return result;
    }

}
